# Generated by Django 4.2.3 on 2023-07-06 11:59

import apps.events.utils
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0002_rename_desc_church_description_alter_church_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('mode', models.CharField(blank=True, choices=[('in-person', 'In Person'), ('virtual', 'Virtual')], default='in-person', max_length=255)),
                ('platform', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('zoom', 'Zoom')], max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('access', models.CharField(blank=True, choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=4)),
                ('entrance_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('banner', models.ImageField(blank=True, default='events/ballons.webp', upload_to=apps.events.utils.event_images_url)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('has_ended', models.BooleanField(default=False)),
                ('has_started', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='churches.church')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-createdAt'],
            },
        ),
    ]
