# Generated by Django 4.2.3 on 2023-09-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, default='events/ballons.webp', upload_to='events/'),
        ),
    ]
