# Generated by Django 4.2.1 on 2023-05-29 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_alter_attendance_options_alter_demographics_options_and_more'),
        ('events', '0002_alter_event_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='church.church'),
        ),
    ]
