# Generated by Django 4.2.3 on 2023-09-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('past', 'Past'), ('unsubmitted', 'Unsubmitted'), ('waiting', 'Waiting Approval')], max_length=255),
        ),
    ]
