# Generated by Django 4.2.3 on 2023-10-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='created_by',
            new_name='editor',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_of_baptism',
        ),
    ]
