# Generated by Django 4.2.3 on 2023-10-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='avatar_fallback_color',
            new_name='avatar_fallback',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='baptised_at',
            new_name='baptized_at',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
