# Generated by Django 4.2.3 on 2023-10-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_rename_created_by_member_editor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='baptised_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
