# Generated by Django 4.2.3 on 2023-10-08 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0007_church_currency'),
        ('people', '0002_rename_avatar_fallback_color_member_avatar_fallback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kin',
            old_name='avatar_fallback_color',
            new_name='avatar_fallback',
        ),
        migrations.RenameField(
            model_name='kin',
            old_name='date_of_baptism',
            new_name='baptized_at',
        ),
        migrations.RenameField(
            model_name='kin',
            old_name='created_by',
            new_name='editor',
        ),
        migrations.RenameField(
            model_name='kin',
            old_name='relation_with_guardian',
            new_name='guardian_relationship',
        ),
        migrations.CreateModel(
            name='ChurchAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('Sunday', 'Sunday'), ('Home', 'Home'), ('Friday', 'Friday'), ('Outreach', 'Outreach'), ('Kids', 'Kids'), ('Adults', 'Adults'), ('Visitors', 'Visitors'), ('New Members', 'New Members'), ('Baptized', 'Baptized'), ('Repented', 'Repented')], max_length=50)),
                ('count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_attendance', to='churches.church')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SundayAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday_attendance', to='people.member')),
            ],
            options={
                'unique_together': {('member', 'date')},
            },
        ),
    ]
