# Generated by Django 4.2.3 on 2023-10-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_rename_created_by_member_editor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='baptized_at',
            new_name='date_of_baptism',
        ),
    ]
