# Generated by Django 4.2.3 on 2023-07-12 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_homecell_hcattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hcattendance',
            name='homecell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hc_attendance', to='people.homecell'),
        ),
    ]
