# Generated by Django 4.2.3 on 2023-10-09 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0007_church_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0003_rename_avatar_fallback_color_kin_avatar_fallback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kindred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('guardian_relationship', models.CharField(blank=True, choices=[('Aunt', 'Aunt'), ('Brother', 'Brother'), ('Child', 'Child'), ('Cousin', 'Cousin'), ('Father', 'Father'), ('Grandparent', 'Grandparent'), ('Mother', 'Mother'), ('Sister', 'Sister'), ('Spouse', 'Spouse'), ('Uncle', 'Uncle')], max_length=255)),
                ('membersince', models.DateField()),
                ('avatar_fallback', models.CharField(blank=True, max_length=24)),
                ('baptized_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kindred', to='churches.church')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kindred_creator', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to='people.member')),
            ],
            options={
                'verbose_name': 'kindred',
                'verbose_name_plural': 'kindred',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='churchattendance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Church Attendance', 'verbose_name_plural': 'Church Attendance'},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='baptized',
            new_name='altar_call',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='home',
            new_name='baptism',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='new',
            new_name='new_members',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='repented',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Kin',
        ),
    ]
