# Generated by Django 4.2.3 on 2023-10-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_rename_baptized_at_member_date_of_baptism'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='baptized_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
