# Generated by Django 4.2.3 on 2023-07-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_hcattendance_homecell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecell',
            name='leader',
        ),
        migrations.AddField(
            model_name='hcattendance',
            name='leader',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hcattendance',
            name='scriptures',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hcattendance',
            name='testimonies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hcattendance',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
