# Generated by Django 4.2.3 on 2023-07-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_homecell_leader_hcattendance_leader_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecell',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='hcattendance',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
