# Generated by Django 4.2.3 on 2023-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_rename_title_homecell_name_hcattendance_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcattendance',
            name='adults',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hcattendance',
            name='kids',
            field=models.BigIntegerField(default=0),
        ),
    ]
