# Generated by Django 4.2.3 on 2023-10-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_attendanceregister_delete_sundayattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceregister',
            options={'ordering': ['-attendance_date'], 'verbose_name': 'attendance register', 'verbose_name_plural': 'attendance register'},
        ),
        migrations.RenameField(
            model_name='attendanceregister',
            old_name='date',
            new_name='attendance_date',
        ),
        migrations.AlterUniqueTogether(
            name='attendanceregister',
            unique_together={('member', 'attendance_date')},
        ),
    ]
