# Generated by Django 4.2.3 on 2023-10-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0007_church_currency'),
        ('people', '0006_alter_attendanceregister_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceregister',
            name='branch',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='member_assembly', to='churches.church'), # type: ignore
            preserve_default=False,
        ),
    ]
