# Generated by Django 4.2.3 on 2023-07-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_hcattendance_adults_hcattendance_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecell',
            name='members',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homecell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='people.homecell')),
            ],
            options={
                'verbose_name': 'testimony',
                'verbose_name_plural': 'testimonies',
                'ordering': ['-created_at'],
            },
        ),
    ]
