# Generated by Django 4.2.3 on 2023-10-09 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_attendanceregister_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
