# Generated by Django 4.2.3 on 2023-07-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_rename_activities_hcattendance_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hcattendance',
            name='testimonies',
        ),
        migrations.AlterField(
            model_name='testimony',
            name='homecell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='people.hcattendance'),
        ),
    ]
