# Generated by Django 4.2.3 on 2023-10-17 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0008_attendanceregister_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hcattendance',
            old_name='leader',
            new_name='coordinator',
        ),
        migrations.AddField(
            model_name='hcattendance',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homecell_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homecell',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homecell_leader', to='people.member'),
        ),
    ]
