# Generated by Django 4.2.3 on 2023-09-29 13:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0007_church_currency'),
        ('people', '0009_remove_hcattendance_testimonies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('relationship', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Engaged', 'Engaged'), ('In a Relationship', 'In a Relationship'), ('Domestic Partnership', 'Domestic Partnership'), ('Civil Union', 'Civil Union'), ('Committed', 'Committed'), ('Common-Law Marriage', 'Common-Law Marriage'), ('Traditional Marriage', 'Traditional Marriage'), ('Co-parenting', 'Co-parenting')], max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('membersince', models.DateField()),
                ('date_of_baptism', models.DateField(blank=True)),
                ('tithes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('ministry', models.CharField(blank=True, choices=[('Administration', 'Administration'), ('Christian education', 'Christian education'), ('Counseling', 'Counseling'), ('Discernment', 'Discernment'), ('Evangelism', 'Evangelism'), ('Giving', 'Giving'), ('Hospitality', 'Hospitality'), ('Intercession', 'Intercession'), ('Leadership', 'Leadership'), ('Media and Communications', 'Media and Communications'), ('Other', 'Other'), ('Praise and Worship', 'Praise and Worship'), ('Ushering', 'Ushering')], max_length=255)),
                ('position', models.CharField(blank=True, choices=[('Sunday School Teacher', 'Sunday School Teacher'), ('Youth Leader', 'Youth Leader'), ('Deacon', 'Deacon'), ('Deaconess', 'Deaconess'), ('Elder', 'Elder'), ('Praise and Worship Director', 'Praise and Worship Director'), ('Pastor', 'Pastor'), ('Senior Pastor', 'Senior Pastor'), ('Overseer', 'Overseer'), ('President', 'President'), ('Media Director', 'Media Director'), ('WOE Leader', 'WOE Leader'), ('Gatekeepers Leader', 'Gatekeepers Leader'), ('House Keeper', 'House Keeper'), ('Home Cell Leader', 'Home Cell Leader'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Other', 'Other')], max_length=255)),
                ('avatar_fallback_color', models.CharField(blank=True, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='churches.church')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
