# Generated by Django 4.2.3 on 2023-10-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_remove_homecell_members_homecell_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecell',
            old_name='name',
            new_name='group_name',
        ),
    ]
