# Generated by Django 4.2.3 on 2023-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_member_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_baptism',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='prefix',
            field=models.CharField(blank=True, choices=[('Dr', 'Dr'), ('Eng', 'Eng'), ('Hon', 'Hon'), ('Miss', 'Miss'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Prof', 'Prof'), ('Rev', 'Rev')], max_length=255),
        ),
    ]
