# Generated by Django 4.2.3 on 2023-10-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_rename_name_homecell_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hcattendance',
            old_name='new',
            new_name='new_members',
        ),
    ]
