# Generated by Django 4.2.3 on 2023-10-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_rename_attendance_hcattendance_total_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hcattendance',
            old_name='repented',
            new_name='altar_call',
        ),
    ]
