# Generated by Django 4.2.3 on 2023-10-19 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0007_church_currency'),
        ('people', '0014_rename_repented_hcattendance_altar_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Friday', 'Friday')], max_length=24)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_branch', to='churches.church')),
                ('members', models.ManyToManyField(blank=True, to='people.member')),
            ],
            options={
                'verbose_name': 'tally',
                'verbose_name_plural': 'tallies',
                'ordering': ['-timestamp'],
            },
        ),
    ]
