# Generated by Django 4.2.3 on 2023-10-03 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churches', '0007_church_currency'),
        ('people', '0014_member_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('avatar_fallback_color', models.CharField(blank=True, max_length=24)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('relationship', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Engaged', 'Engaged'), ('In a Relationship', 'In a Relationship'), ('Domestic Partnership', 'Domestic Partnership'), ('Civil Union', 'Civil Union'), ('Committed', 'Committed'), ('Common-Law Marriage', 'Common-Law Marriage'), ('Traditional Marriage', 'Traditional Marriage'), ('Co-parenting', 'Co-parenting')], max_length=255)),
                ('membersince', models.DateField()),
                ('date_of_baptism', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kin', to='churches.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_admin', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to='people.member')),
            ],
            options={
                'verbose_name': 'kin',
                'verbose_name_plural': 'kins',
                'ordering': ['-created_at'],
            },
        ),
    ]
