# Generated by Django 4.2.3 on 2023-10-30 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_tally'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecell',
            options={'ordering': ['group_name'], 'verbose_name': 'homecell', 'verbose_name_plural': 'homecells'},
        ),
    ]
