# Generated by Django 4.2.3 on 2023-10-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_remove_kin_relationship_kin_relation_with_guardian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kin',
            name='relation_with_guardian',
            field=models.CharField(blank=True, choices=[('Aunt', 'Aunt'), ('Brother', 'Brother'), ('Child', 'Child'), ('Cousin', 'Cousin'), ('Father', 'Father'), ('Grandparent', 'Grandparent'), ('Mother', 'Mother'), ('Sister', 'Sister'), ('Spouse', 'Spouse'), ('Uncle', 'Uncle')], max_length=255),
        ),
    ]
