# Generated by Django 4.2.3 on 2023-10-31 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0016_alter_homecell_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='preacher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scriptures',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sermon',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tally',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tally_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kindred',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kindred_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
