# Generated by Django 4.2.3 on 2023-11-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_attendance_editor_attendance_preacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecell',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
