# Generated by Django 4.2.3 on 2023-10-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_alter_kin_relation_with_guardian'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecell',
            options={'ordering': ['-created_at'], 'verbose_name': 'Homecell', 'verbose_name_plural': 'Homecells'},
        ),
    ]
