# Generated by Django 4.2.3 on 2023-11-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_homecell_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hcattendance',
            options={'ordering': ['start_time'], 'verbose_name': 'Homecell Attendance', 'verbose_name_plural': 'Homecell Attendance'},
        ),
        migrations.AlterField(
            model_name='hcattendance',
            name='homecell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homecell_attendance', to='people.homecell'),
        ),
    ]
