# Generated by Django 4.2.3 on 2023-11-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_alter_hcattendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindred',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian', to='people.member'),
        ),
    ]
