# Generated by Django 4.2.9 on 2024-01-25 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_remove_churchattendance_church_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kindred',
            old_name='editor',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='kindred',
            name='membership_status',
            field=models.CharField(blank=True, choices=[('Established', 'Established'), ('Newcomer', 'Newcomer')], default='Established', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1899, 12, 31, 21, 49, 40, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1899, 12, 31, 21, 49, 40, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='baptized_at',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True),
        ),
    ]
