# Generated by Django 4.2.9 on 2024-01-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_rename_editor_kindred_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tally',
            old_name='editor',
            new_name='created_by',
        ),
    ]
