# Generated by Django 4.2.9 on 2024-01-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0012_alter_church_status'),
        ('people', '0023_rename_editor_tally_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='editor',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='attendance',
            name='homecell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homecell_attendance', to='people.homecell'),
        ),
        migrations.AlterField(
            model_name='hcattendance',
            name='homecell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homecell_attend', to='people.homecell'),
        ),
        migrations.AlterField(
            model_name='tally',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_branch', to='churches.church'),
        ),
    ]
