# Generated by Django 4.2.9 on 2024-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_alter_attendance_options_alter_tally_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-attendance_date'], 'verbose_name': 'attendance', 'verbose_name_plural': 'attendance'},
        ),
        migrations.AlterModelOptions(
            name='homecell',
            options={'ordering': ['-created_at'], 'verbose_name': 'homecell', 'verbose_name_plural': 'homecells'},
        ),
        migrations.AlterModelOptions(
            name='tally',
            options={'ordering': ['-timestamp'], 'verbose_name': 'tally', 'verbose_name_plural': 'tallies'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='category',
            field=models.CharField(blank=True, choices=[('friday', 'Friday Prayer'), ('homecell', 'Homecell'), ('outreach', 'Outreach'), ('other', 'Other'), ('sunday', 'Sunday')], default='sunday', max_length=24),
        ),
        migrations.AlterField(
            model_name='tally',
            name='category',
            field=models.CharField(blank=True, choices=[('friday', 'Friday Prayer'), ('homecell', 'Homecell'), ('outreach', 'Outreach'), ('other', 'Other'), ('sunday', 'Sunday')], default='sunday', max_length=24),
        ),
    ]
