# Generated by Django 4.2.9 on 2024-04-29 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0012_alter_church_status'),
        ('people', '0027_homecell_non_church_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecell',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homecell', to='churches.church'),
        ),
    ]
