# Generated by Django 4.2.9 on 2024-06-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_rename_attendance_count_attendance_headcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='category',
            field=models.CharField(blank=True, choices=[('friday', 'Friday'), ('homecell', 'Homecell'), ('outreach', 'Outreach'), ('other', 'Other'), ('sunday', 'Sunday')], default='sunday', max_length=24),
        ),
        migrations.AlterField(
            model_name='tally',
            name='category',
            field=models.CharField(blank=True, choices=[('friday', 'Friday'), ('homecell', 'Homecell'), ('outreach', 'Outreach'), ('other', 'Other'), ('sunday', 'Sunday')], default='sunday', max_length=24),
        ),
    ]
