# Generated by Django 4.2.9 on 2024-10-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0031_rename_kindred_juniormember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-timestamp'], 'verbose_name': 'attendance', 'verbose_name_plural': 'attendance'},
        ),
        migrations.AlterModelOptions(
            name='juniormember',
            options={'ordering': ['-created_at'], 'verbose_name': 'Junior Member', 'verbose_name_plural': 'Junior Members'},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance_date',
            new_name='timestamp',
        ),
    ]
