# Generated by Django 4.2.9 on 2025-03-10 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0032_alter_attendance_options_alter_juniormember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1899, 12, 31, 21, 49, 42, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1899, 12, 31, 21, 49, 42, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
