# Generated by Django 4.2.9 on 2025-03-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0033_alter_attendance_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='tithes',
        ),
    ]
