# Generated by Django 4.2.9 on 2025-03-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0035_member_address_line2_member_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='church',
            new_name='assembly',
        ),
    ]
