# Generated by Django 4.2.9 on 2025-03-31 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_rename_church_member_assembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='baptized_at',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membersince',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True),
        ),
    ]
