# Generated by Django 4.2.9 on 2025-03-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0037_alter_member_baptized_at_alter_member_membersince'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_key',
            field=models.CharField(blank=True, editable=False, max_length=21, null=True, unique=True),
        ),
    ]
