# Generated by Django 4.2.9 on 2025-03-31 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0040_ministry_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'verbose_name': 'Ministry', 'verbose_name_plural': 'Ministries'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='ministry',
        ),
        migrations.RemoveField(
            model_name='member',
            name='position',
        ),
    ]
