# Generated by Django 4.2.9 on 2025-03-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0041_alter_ministry_options_remove_member_ministry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ministries',
            field=models.ManyToManyField(blank=True, to='people.ministry'),
        ),
        migrations.AddField(
            model_name='member',
            name='positions',
            field=models.ManyToManyField(blank=True, to='people.position'),
        ),
    ]
