# Generated by Django 4.2.9 on 2025-03-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0042_member_ministries_member_positions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone_number_line2',
            new_name='secondary_phone_number',
        ),
    ]
