# Generated by Django 4.2.9 on 2025-04-12 16:59

import apps.people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0043_rename_phone_number_line2_member_secondary_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_key',
            field=models.CharField(blank=True, default=apps.people.models.generate_member_id, editable=False, max_length=21, null=True, unique=True),
        ),
    ]
