# Generated by Django 4.2.9 on 2025-05-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0043_rename_phone_number_line2_member_secondary_phone_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='member',
            name='unique_member_identity',
        ),
        migrations.RenameField(
            model_name='juniormember',
            old_name='member_id',
            new_name='member_key',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_key',
        ),
        migrations.AddField(
            model_name='member',
            name='access_pin',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='member',
            name='pin_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'date_of_birth', 'phone_number'), name='unique_member_keyentity'),
        ),
    ]
