# Generated by Django 4.2.9 on 2025-04-12 16:59

import apps.people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0044_alter_member_member_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_key',
            field=models.CharField(default=apps.people.models.generate_member_key, editable=False, max_length=21, unique=True),
        ),
    ]
