# Generated by Django 4.2.9 on 2025-05-07 16:39

import apps.people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0044_remove_member_unique_member_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_key',
            field=models.CharField(blank=True, default=apps.people.models.generate_member_key, editable=False, max_length=21, null=True, unique=True),
        ),
    ]
