# Generated by Django 4.2.9 on 2025-05-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0044_remove_member_unique_member_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar_fallback',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
