# Generated by Django 4.2.9 on 2025-05-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0045_member_member_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='member',
            name='unique_member_identity',
        ),
        migrations.RemoveField(
            model_name='juniormember',
            name='member_id',
        ),
    ]
