# Generated by Django 4.2.9 on 2025-04-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0045_alter_member_member_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_key',
            new_name='member_id',
        ),
    ]
