# Generated by Django 4.2.9 on 2025-05-07 17:50

import apps.people.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0046_remove_member_unique_member_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juniormember',
            name='member_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_key',
            field=models.CharField(default=apps.people.models.generate_member_key, editable=False, max_length=21, unique=True),
        ),
    ]
