# Generated by Django 4.2.9 on 2025-04-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0046_rename_member_key_member_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='access_pin',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='member',
            name='pin_set',
            field=models.BooleanField(default=False),
        ),
    ]
