# Generated by Django 4.2.9 on 2025-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0047_member_access_pin_member_pin_set'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='member',
            name='unique_member_identity',
        ),
        migrations.RenameField(
            model_name='juniormember',
            old_name='member_id',
            new_name='member_key',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_id',
            new_name='member_key',
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'date_of_birth', 'phone_number'), name='unique_member_keyentity'),
        ),
    ]
