# Generated by Django 4.2.9 on 2025-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0047_alter_member_ministries_alter_member_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniormember',
            name='membership_status',
            field=models.CharField(blank=True, choices=[('Visitor', 'Visitor'), ('Regular', 'Regular Attendee'), ('Established', 'Established'), ('Relocated', 'Relocated (Living Abroad)'), ('Inactive', 'Inactive'), ('Transferred', 'Transferred to Another Church'), ('Deceased', 'Deceased')], default='Established', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Diploma', 'Diploma'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctorate', 'Doctorate'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_status',
            field=models.CharField(blank=True, choices=[('Visitor', 'Visitor'), ('Regular', 'Regular Attendee'), ('Established', 'Established'), ('Relocated', 'Relocated (Living Abroad)'), ('Inactive', 'Inactive'), ('Transferred', 'Transferred to Another Church'), ('Deceased', 'Deceased')], default='Established', max_length=255),
        ),
    ]
