# Generated by Django 4.2.9 on 2025-05-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0048_alter_juniormember_membership_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='trash_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
