# Generated by Django 4.2.9 on 2025-05-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0049_alter_member_member_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_key',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
