# Generated by Django 4.2.9 on 2025-05-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0049_member_is_trash_member_trash_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
    ]
