# Generated by Django 4.2.9 on 2025-09-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('people', '0051_attendance_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='reports.unifiedreport'),
        ),
    ]
