# Generated by Django 4.2.9 on 2026-02-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0052_alter_attendance_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='baptism',
            new_name='baptisms',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='visitors',
            new_name='guest_attendance',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='newcomers',
            new_name='new_converts',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='summary',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='achievements',
        ),
        migrations.AddField(
            model_name='attendance',
            name='followups_scheduled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_special_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='online_viewers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='service_type',
            field=models.CharField(choices=[('main', 'Main Service'), ('bible_study', 'Bible Study'), ('prayer', 'Prayer')], db_index=True, default='main', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_leaders_present',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='volunteers_on_duty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
