# Generated by Django 4.2.9 on 2026-02-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0053_rename_baptism_attendance_baptisms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='headcount',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='start_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='weather',
            field=models.CharField(blank=True, choices=[('sunny', 'Sunny'), ('partly_cloudy', 'Partly Cloudy'), ('cloudy', 'Cloudy'), ('windy', 'Windy'), ('light_rain', 'Light Rain'), ('heavy_rain', 'Heavy Rain'), ('storm', 'Storm'), ('very_hot', 'Very Hot'), ('cold', 'Cold'), ('extreme', 'Extreme Weather')], db_index=True, max_length=30, null=True),
        ),
    ]
