# Generated by Django 4.2.9 on 2026-02-25 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0054_remove_attendance_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='special_event_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='altar_call',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='baptisms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='guest_attendance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='new_converts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(1900, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='hcattendance',
            name='adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hcattendance',
            name='altar_call',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hcattendance',
            name='kids',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hcattendance',
            name='new_members',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hcattendance',
            name='total_attendance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hcattendance',
            name='visitors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
