# Generated by Django 4.2.9 on 2026-02-25 22:36

import datetime

from django.db import migrations, models


ATTENDANCE_COUNT_FIELDS = (
    "adults",
    "altar_call",
    "baptisms",
    "children",
    "guest_attendance",
    "new_converts",
)


def normalize_negative_attendance_counts(apps, schema_editor):
    """
    Historical Attendance data contains a small number of negative count
    values caused by legacy data-entry errors.

    Convert negative counts to their absolute values before changing these
    columns to PositiveIntegerField.

    Examples:
        -1 -> 1
        -5 -> 5

    Original values have been preserved in the pre-migration evidence export.
    """
    Attendance = apps.get_model("people", "Attendance")

    for field_name in ATTENDANCE_COUNT_FIELDS:
        queryset = Attendance.objects.filter(
            **{f"{field_name}__lt": 0}
        )

        for attendance in queryset.iterator():
            current_value = getattr(attendance, field_name)

            setattr(
                attendance,
                field_name,
                abs(current_value),
            )

            attendance.save(
                update_fields=[field_name]
            )


def noop_reverse(apps, schema_editor):
    # The original negative legacy values cannot be reconstructed
    # automatically. They are retained in the external migration evidence.
    pass


class Migration(migrations.Migration):
    # Historical data is normalized before PostgreSQL adds
    # PositiveIntegerField constraints to the same table.
    #
    # This must be non-atomic so the data updates commit before
    # subsequent ALTER TABLE operations. Otherwise PostgreSQL reports
    # pending trigger events.
    atomic = False

    dependencies = [
        ('people', '0054_remove_attendance_end_time_and_more'),
    ]

    operations = [
        migrations.RunPython(
            normalize_negative_attendance_counts,
            noop_reverse,
        ),

        migrations.AddField(
            model_name='attendance',
            name='special_event_name',
            field=models.CharField(
                blank=True,
                max_length=255,
            ),
        ),

        # Correct legacy negative count values before PostgreSQL creates
        # the non-negative CHECK constraints associated with
        # PositiveIntegerField.
        
        migrations.AlterField(
            model_name='attendance',
            name='adults',
            field=models.PositiveIntegerField(default=0),
        ),

        migrations.AlterField(
            model_name='attendance',
            name='altar_call',
            field=models.PositiveIntegerField(default=0),
        ),

        migrations.AlterField(
            model_name='attendance',
            name='baptisms',
            field=models.PositiveIntegerField(default=0),
        ),

        migrations.AlterField(
            model_name='attendance',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),

        migrations.AlterField(
            model_name='attendance',
            name='guest_attendance',
            field=models.PositiveIntegerField(default=0),
        ),

        migrations.AlterField(
            model_name='attendance',
            name='new_converts',
            field=models.PositiveIntegerField(default=0),
        ),

        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateField(
                blank=True,
                db_index=True,
                default=datetime.date(1900, 1, 1),
                null=True,
            ),
        ),

        # HCAttendance is retained as a physical legacy archive.
        # Update Django's historical migration state without modifying
        # the PostgreSQL archive table itself.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='hcattendance',
                    name='adults',
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AlterField(
                    model_name='hcattendance',
                    name='altar_call',
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AlterField(
                    model_name='hcattendance',
                    name='kids',
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AlterField(
                    model_name='hcattendance',
                    name='new_members',
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AlterField(
                    model_name='hcattendance',
                    name='total_attendance',
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AlterField(
                    model_name='hcattendance',
                    name='visitors',
                    field=models.PositiveIntegerField(default=0),
                ),
            ],
        ),
    ]