# Generated by Django 4.2.9 on 2026-03-04 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0033_alter_zone_code'),
        ('reports', '0011_remove_assemblyreport_unique_assembly_report_period_and_more'),
        ('people', '0055_attendance_special_event_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hcattendance',
            name='church',
        ),
        migrations.RemoveField(
            model_name='hcattendance',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='hcattendance',
            name='homecell',
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='category',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='churches.church'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='homecell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='people.homecell'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='reports.assemblyreport'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='service_type',
            field=models.CharField(choices=[('friday', 'Friday'), ('homecell', 'Homecell'), ('outreach', 'Outreach'), ('other', 'Other'), ('sunday', 'Sunday')], db_index=True, default='sunday', max_length=24),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('church', 'timestamp', 'service_type', 'homecell'), name='unique_service_attendance'),
        ),
        migrations.DeleteModel(
            name='HCAttendance',
        ),
    ]
