# Generated by Django 4.2.9 on 2026-03-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0056_remove_hcattendance_church_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='followups_scheduled',
        ),
    ]
