# Generated by Django 4.2.9 on 2026-03-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0057_remove_attendance_followups_scheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='slug',
        ),
    ]
