# Generated by Django 4.2.9 on 2026-03-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0058_remove_attendance_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_service_attendance',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='church',
            new_name='assembly',
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('assembly', 'timestamp', 'service_type', 'homecell'), name='unique_service_attendance'),
        ),
    ]
