# Generated by Django 4.2.9 on 2026-03-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0059_remove_attendance_unique_service_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_by',
        ),
    ]
