# Generated by Django 6.0.3 on 2026-03-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0060_remove_attendance_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
