# Generated by Django 6.0.3 on 2026-03-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0062_uploadsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadSession',
        ),
    ]
