# Generated by Django 6.0.3 on 2026-05-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0063_delete_uploadsession'),
        ('reports', '0016_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_set', to='reports.assemblyreport'),
        ),
    ]
