# Generated by Codex on 2026-06-28

import django.conf
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churches", "0051_alter_church_code"),
        ("people", "0064_alter_attendance_report"),
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SundaySchoolAttendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("service_date", models.DateField(db_index=True)),
                (
                    "class_name",
                    models.CharField(
                        choices=[
                            ("beginners", "Beginners"),
                            ("primary", "Primary"),
                            ("juniors", "Juniors"),
                            ("intermediate", "Intermediate"),
                            ("teens", "Teens"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("boys", models.PositiveIntegerField(default=0)),
                ("girls", models.PositiveIntegerField(default=0)),
                ("male_visitors", models.PositiveIntegerField(default=0)),
                ("female_visitors", models.PositiveIntegerField(default=0)),
                ("male_first_timers", models.PositiveIntegerField(default=0)),
                ("female_first_timers", models.PositiveIntegerField(default=0)),
                ("lesson_title", models.CharField(blank=True, max_length=255)),
                ("scripture_reference", models.CharField(blank=True, max_length=120)),
                ("offering", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assembly",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sunday_school_attendances",
                        to="churches.church",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_sunday_school_attendances",
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_sunday_school_attendances",
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sunday_school_attendances",
                        to="people.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sunday School Attendance",
                "verbose_name_plural": "Sunday School Attendance",
                "ordering": ["-service_date", "class_name"],
            },
        ),
        migrations.AddIndex(
            model_name="sundayschoolattendance",
            index=models.Index(fields=["assembly", "service_date"], name="people_sund_assembl_3123e1_idx"),
        ),
        migrations.AddIndex(
            model_name="sundayschoolattendance",
            index=models.Index(fields=["assembly", "status"], name="people_sund_assembl_914d7e_idx"),
        ),
        migrations.AddIndex(
            model_name="sundayschoolattendance",
            index=models.Index(fields=["teacher", "service_date"], name="people_sund_teacher_419291_idx"),
        ),
        migrations.AddConstraint(
            model_name="sundayschoolattendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("assembly", "class_name", "service_date"),
                name="unique_active_sunday_school_attendance",
            ),
        ),
    ]
