# Generated by Django 6.0.3 on 2026-06-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0065_sundayschoolattendance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sundayschoolattendance',
            new_name='people_sund_assembl_64cd9b_idx',
            old_name='people_sund_assembl_3123e1_idx',
        ),
        migrations.RenameIndex(
            model_name='sundayschoolattendance',
            new_name='people_sund_assembl_3a1cc8_idx',
            old_name='people_sund_assembl_914d7e_idx',
        ),
        migrations.RenameIndex(
            model_name='sundayschoolattendance',
            new_name='people_sund_teacher_9144db_idx',
            old_name='people_sund_teacher_419291_idx',
        ),
    ]
