# Generated by Django 6.0.3 on 2026-07-13 22:07

import apps.people.models.former_members
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_membership_lifecycle(apps, schema_editor):
    """Preserve 0068 rows while separating lifecycle from member classification.

    Legacy values remain in ``Member.membership_status`` for API compatibility.
    We do not invent a date of death: the old status contains no trustworthy date.
    """
    Member = apps.get_model("people", "Member")
    Membership = apps.get_model("people", "AssemblyMembership")
    Transfer = apps.get_model("people", "MemberTransferRequest")

    stage_map = {
        "Visitor": "new",
        "Regular": "associate",
        "Established": "established",
    }
    for member in Member.objects.all().iterator():
        member.membership_stage = stage_map.get(member.membership_status, "established")
        update_fields = ["membership_stage"]
        current = Membership.objects.filter(member_id=member.pk).exclude(status="transferred").first()
        if member.membership_status == "Inactive" and current:
            current.status = "inactive"
            current.ended_on = None
            current.end_reason = ""
            current.save(update_fields=["status", "ended_on", "end_reason"])
        elif member.membership_status == "Deceased" and current:
            ended_on = member.updated_at.date() if member.updated_at else current.joined_on
            current.status = "ended"
            current.ended_on = max(ended_on, current.joined_on)
            current.end_reason = "deceased"
            current.save(update_fields=["status", "ended_on", "end_reason"])
            member.assembly_id = None
            update_fields.append("assembly")
        member.save(update_fields=update_fields)

    for membership in Membership.objects.filter(status="transferred").iterator():
        transfer = Transfer.objects.filter(
            member_id=membership.member_id,
            from_assembly_id=membership.assembly_id,
            status="completed",
        ).order_by("completed_at", "pk").first()
        membership.status = "ended"
        membership.ended_on = membership.ended_on or (
            transfer.effective_date if transfer else membership.joined_on
        )
        if membership.ended_on < membership.joined_on:
            membership.ended_on = membership.joined_on
        if transfer:
            membership.end_reason = "transferred"
            membership.transfer_id = transfer.pk
        else:
            membership.end_reason = "other"
            membership.end_notes = (
                "Migrated from legacy 'transferred' status without a matching completed transfer."
            )
        membership.save(update_fields=[
            "status", "ended_on", "end_reason", "end_notes", "transfer"
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0051_alter_church_code'),
        ('people', '0068_member_transfer_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_key', models.CharField(default=apps.people.models.former_members.generate_household_key, editable=False, max_length=21, unique=True)),
                ('name', models.CharField(help_text='For example: Zhuwao Household', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=17)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Household',
                'verbose_name_plural': 'Households',
                'ordering': ['name', 'household_key'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head', 'Head of Household'), ('spouse', 'Spouse'), ('adult', 'Adult'), ('child', 'Child'), ('dependent', 'Dependent'), ('relative', 'Relative'), ('other', 'Other')], default='other', max_length=20)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate)),
                ('left_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Household Member',
                'verbose_name_plural': 'Household Members',
                'ordering': ['-joined_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormerMember',
            fields=[
            ],
            options={
                'verbose_name': 'Former Member',
                'verbose_name_plural': 'Former Members',
                'ordering': ['-ended_on', '-updated_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('people.assemblymembership',),
        ),
        migrations.AlterModelOptions(
            name='assemblymembership',
            options={'ordering': ['-joined_on', '-created_at'], 'verbose_name': 'Assembly Membership', 'verbose_name_plural': 'Assembly Memberships'},
        ),
        migrations.RemoveConstraint(
            model_name='assemblymembership',
            name='unique_active_assembly_membership_per_member',
        ),
        migrations.RemoveIndex(
            model_name='assemblymembership',
            name='people_asse_member__ecbaea_idx',
        ),
        migrations.RemoveIndex(
            model_name='assemblymembership',
            name='people_asse_assembl_de3426_idx',
        ),
        migrations.RemoveIndex(
            model_name='assemblymembership',
            name='people_asse_status_fa3f39_idx',
        ),
        migrations.RemoveIndex(
            model_name='assemblymembership',
            name='people_asse_start_d_a4003d_idx',
        ),
        migrations.RemoveIndex(
            model_name='assemblymembership',
            name='people_asse_end_dat_47c6a2_idx',
        ),
        migrations.RenameField(
            model_name='assemblymembership',
            old_name='end_date',
            new_name='ended_on',
        ),
        migrations.AddField(
            model_name='assemblymembership',
            name='end_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assemblymembership',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('transferred', 'Transferred'), ('resigned', 'Resigned'), ('relocated', 'Relocated'), ('removed', 'Removed'), ('deceased', 'Deceased'), ('lost_contact', 'Lost Contact'), ('duplicate', 'Duplicate Record'), ('other', 'Other')], max_length=30),
        ),
        migrations.RenameField(
            model_name='assemblymembership',
            old_name='start_date',
            new_name='joined_on',
        ),
        migrations.AddField(
            model_name='assemblymembership',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_membership_changes', to='people.membertransferrequest'),
        ),
        migrations.AddField(
            model_name='assemblymembership',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assembly_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_stage',
            field=models.CharField(choices=[('new', 'New'), ('established', 'Established'), ('associate', 'Associate')], default='established', help_text='Membership maturity/classification; lifecycle is stored on AssemblyMembership.', max_length=20),
        ),
        migrations.RunPython(migrate_membership_lifecycle, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='assemblymembership',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_memberships', to='churches.church'),
        ),
        migrations.AlterField(
            model_name='assemblymembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('ended', 'Ended')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='churches.church'),
        ),
        migrations.AddIndex(
            model_name='assemblymembership',
            index=models.Index(fields=['assembly', 'status'], name='people_asse_assembl_4a09ee_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblymembership',
            index=models.Index(fields=['member', 'status'], name='people_asse_member__f999be_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblymembership',
            index=models.Index(fields=['assembly', 'ended_on'], name='people_asse_assembl_9f9e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblymembership',
            index=models.Index(fields=['assembly', 'end_reason'], name='people_asse_assembl_cba3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblymembership',
            index=models.Index(fields=['member', 'joined_on'], name='people_asse_member__c78dd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='assemblymembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'inactive'])), fields=('member',), name='one_current_assembly_membership_per_member'),
        ),
        migrations.AddConstraint(
            model_name='assemblymembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_on__isnull', False), ('status', 'ended')), models.Q(('ended_on__isnull', True), ('status__in', ['active', 'inactive'])), _connector='OR'), name='assembly_membership_valid_end_date'),
        ),
        migrations.AddConstraint(
            model_name='assemblymembership',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('joined_on')), _connector='OR'), name='assembly_membership_ended_after_joining'),
        ),
        migrations.AddConstraint(
            model_name='assemblymembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ended'), _negated=True), models.Q(('end_reason', ''), _negated=True), _connector='OR'), name='ended_membership_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='assemblymembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_reason', 'transferred'), _negated=True), ('transfer__isnull', False), _connector='OR'), name='transferred_membership_requires_transfer'),
        ),
        migrations.AddField(
            model_name='household',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='households', to='churches.church'),
        ),
        migrations.AddField(
            model_name='household',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_households', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_households', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_household_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to='people.household'),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to='people.member'),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_household_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['assembly', 'status'], name='people_hous_assembl_184bca_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['assembly', 'name'], name='people_hous_assembl_eddac4_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['household_key'], name='people_hous_househo_adc495_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['phone_number'], name='people_hous_phone_n_84fdf3_idx'),
        ),
        migrations.AddIndex(
            model_name='householdmember',
            index=models.Index(fields=['household', 'left_on'], name='people_hous_househo_c29a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='householdmember',
            index=models.Index(fields=['member', 'left_on'], name='people_hous_member__ea7130_idx'),
        ),
        migrations.AddIndex(
            model_name='householdmember',
            index=models.Index(fields=['household', 'role'], name='people_hous_househo_b07768_idx'),
        ),
        migrations.AddIndex(
            model_name='householdmember',
            index=models.Index(fields=['household', 'is_primary_contact'], name='people_hous_househo_a40602_idx'),
        ),
        migrations.AddConstraint(
            model_name='householdmember',
            constraint=models.UniqueConstraint(condition=models.Q(('left_on__isnull', True)), fields=('member',), name='one_active_household_per_member'),
        ),
        migrations.AddConstraint(
            model_name='householdmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_contact', True), ('left_on__isnull', True)), fields=('household',), name='one_primary_contact_per_household'),
        ),
        migrations.AddConstraint(
            model_name='householdmember',
            constraint=models.CheckConstraint(condition=models.Q(('left_on__isnull', True), ('left_on__gte', models.F('joined_on')), _connector='OR'), name='household_left_on_after_joined_on'),
        ),
    ]
