# Generated by Django 6.0.3 on 2026-07-13 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0069_household_householdmember_formermember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblymembership',
            name='joined_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
