# Generated by Django 6.0.3 on 2026-07-13 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0051_alter_church_code'),
        ('people', '0070_alter_assemblymembership_joined_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membertransferrequest',
            name='unique_pending_transfer_per_member',
        ),
        migrations.AddConstraint(
            model_name='membertransferrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_acceptance', 'accepted'])), fields=('member',), name='unique_open_transfer_per_member'),
        ),
    ]
