# Generated by Django 5.2.16 on 2026-08-30 02:39

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0051_alter_church_code'),
        ('people', '0072_historical_attendance_and_sunday_school_report'),
        ('reports', '0024_historical_migration_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-created_at'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_service_attendance',
        ),
        migrations.RemoveConstraint(
            model_name='member',
            name='unique_member_keyentity',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_trash',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='sundayschoolattendance',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('assembly', 'timestamp', 'service_type', 'homecell'), name='unique_service_attendance'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('is_trash', False)), fields=('first_name', 'last_name', 'date_of_birth', 'phone_number'), name='unique_member_keyentity'),
        ),
    ]
