# Generated by Django 4.2.1 on 2023-05-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateTimeField()),
                ('week_end', models.DateTimeField()),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='church.church')),
            ],
            options={
                'verbose_name': 'calendar',
                'verbose_name_plural': 'calendar',
                'ordering': ['week_start'],
            },
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('sun_service', models.BigIntegerField(default=0)),
                ('cell_meeting', models.BigIntegerField(default=0)),
                ('fri_prayer', models.BigIntegerField(default=0)),
                ('outreach', models.BigIntegerField(default=0)),
                ('kids', models.BigIntegerField(default=0)),
                ('adults', models.BigIntegerField(default=0)),
                ('visitors', models.BigIntegerField(default=0)),
                ('new_members', models.BigIntegerField(default=0)),
                ('baptism', models.BigIntegerField(default=0)),
                ('repented', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='church.church')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='church.calendar')),
            ],
            options={
                'verbose_name': 'demographics',
                'verbose_name_plural': 'demographics',
                'ordering': ['-created_at'],
            },
        ),
    ]
