# Generated by Django 4.2.1 on 2023-05-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_calendar_demographics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun_service', models.BigIntegerField(default=0)),
                ('cell_meeting', models.BigIntegerField(default=0)),
                ('fri_prayer', models.BigIntegerField(default=0)),
                ('outreach', models.BigIntegerField(default=0)),
                ('kids', models.BigIntegerField(default=0)),
                ('adults', models.BigIntegerField(default=0)),
                ('visitors', models.BigIntegerField(default=0)),
                ('new_members', models.BigIntegerField(default=0)),
                ('baptism', models.BigIntegerField(default=0)),
                ('repented', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'demographics',
                'verbose_name_plural': 'demographics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='demographics',
            options={'ordering': ['week_start'], 'verbose_name': 'calendar', 'verbose_name_plural': 'calendar'},
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='baptism',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='cell_meeting',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='fri_prayer',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='new_members',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='outreach',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='period',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='repented',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='sun_service',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='visitors',
        ),
        migrations.AddField(
            model_name='demographics',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='church.church'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='week_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='week_start',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='church.demographics'),
        ),
    ]
