# Generated by Django 4.2.1 on 2023-05-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_attendance_alter_demographics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-created_at'], 'verbose_name': 'attendance', 'verbose_name_plural': 'attendance'},
        ),
        migrations.AlterModelOptions(
            name='demographics',
            options={'ordering': ['week_start'], 'verbose_name': 'demographics', 'verbose_name_plural': 'demographics'},
        ),
        migrations.AlterField(
            model_name='demographics',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='church.church'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='week_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='week_start',
            field=models.DateField(),
        ),
    ]
