# Generated by Django 4.2.1 on 2023-06-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_alter_attendance_options_alter_demographics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='code',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
