# Generated by Django 4.2.1 on 2023-06-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_church_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographics',
            name='church',
        ),
        migrations.RemoveField(
            model_name='member',
            name='church',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Demographics',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
