# Generated by Django 4.2.1 on 2023-07-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_church_pastor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='pastor',
        ),
    ]
