# Generated by Django 4.2.3 on 2023-07-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='church',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
