# Generated by Django 4.2.3 on 2023-08-10 06:35

import apps.churches.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0002_rename_desc_church_description_alter_church_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.churches.utils.church_images_path),
        ),
        migrations.AddField(
            model_name='church',
            name='header',
            field=models.ImageField(blank=True, upload_to=apps.churches.utils.church_images_path),
        ),
    ]
