# Generated by Django 4.2.3 on 2023-09-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0004_rename_header_church_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='lang',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
