# Generated by Django 4.2.3 on 2023-09-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0005_church_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='brand',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
