# Generated by Django 4.2.3 on 2023-12-23 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churches', '0007_church_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='pastor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastor', to=settings.AUTH_USER_MODEL),
        ),
    ]
