# Generated by Django 4.2.3 on 2023-12-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0008_church_pastor'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
    ]
