# Generated by Django 4.2.3 on 2023-12-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0009_church_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['church_name'], 'verbose_name': 'church', 'verbose_name_plural': 'churches'},
        ),
        migrations.RenameField(
            model_name='church',
            old_name='name',
            new_name='church_name',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
