# Generated by Django 4.2.3 on 2023-12-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0010_alter_church_options_rename_name_church_church_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['name'], 'verbose_name': 'church', 'verbose_name_plural': 'churches'},
        ),
        migrations.RenameField(
            model_name='church',
            old_name='church_name',
            new_name='name',
        ),
    ]
