# Generated by Django 5.0.1 on 2024-01-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0011_alter_church_options_rename_church_name_church_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
    ]
