# Generated by Django 4.2.9 on 2024-05-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0014_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='server_action/'),
        ),
    ]
