# Generated by Django 4.2.9 on 2024-06-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0015_alter_imageupload_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageupload',
            options={'ordering': ['-created_at'], 'verbose_name': 'image upload', 'verbose_name_plural': 'image upload'},
        ),
    ]
