# Generated by Django 4.2.9 on 2025-01-19 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churches', '0016_alter_imageupload_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='church_id',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='church',
            name='pastor',
        ),
        migrations.AddField(
            model_name='church',
            name='pastors',
            field=models.ManyToManyField(blank=True, related_name='pastor_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
