# Generated by Django 4.2.9 on 2025-01-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0017_rename_church_id_church_uuid_remove_church_pastor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='pastors',
            new_name='assigned_pastors',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='code',
            new_name='iso_country_code',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='lang',
            new_name='language',
        ),
    ]
