# Generated by Django 4.2.9 on 2025-01-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0018_rename_pastors_church_assigned_pastors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='banner',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='avatar_fallback',
            new_name='fallback_image',
        ),
        migrations.RenameField(
            model_name='church',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
