# Generated by Django 4.2.9 on 2025-03-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0019_rename_banner_church_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='fallback_image',
            new_name='avatar_fallback',
        ),
    ]
