# Generated by Django 4.2.9 on 2025-03-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0020_rename_fallback_image_church_avatar_fallback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='avatar_fallback',
            field=models.CharField(blank=True, max_length=26),
        ),
    ]
