# Generated by Django 4.2.9 on 2025-06-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0022_alter_church_avatar_fallback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='iso_country_code',
            new_name='country_code',
        ),
    ]
