# Generated by Django 4.2.9 on 2025-08-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0023_rename_iso_country_code_church_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
