# Generated by Django 4.2.9 on 2025-09-15 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0024_church_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator', models.CharField(max_length=255)),
                ('overseer', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='churches.church')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='churches.zonename')),
            ],
        ),
    ]
