# Generated by Django 4.2.9 on 2025-09-15 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0025_zonename_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='church',
        ),
        migrations.AddField(
            model_name='church',
            name='zone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='churches.zone'),
        ),
    ]
