# Generated by Django 4.2.9 on 2025-09-15 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churches', '0026_remove_zone_church_church_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='zone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_zone', to='churches.zone'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zone',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='overseer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_overseers', to=settings.AUTH_USER_MODEL),
        ),
    ]
