# Generated by Django 4.2.9 on 2025-09-15 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churches', '0027_zone_updated_at_alter_church_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='overseer',
        ),
        migrations.AddField(
            model_name='zone',
            name='admins',
            field=models.ManyToManyField(related_name='zones_as_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zone',
            name='overseers',
            field=models.ManyToManyField(related_name='zones_as_overseer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone', to='churches.zonename'),
        ),
    ]
