# Generated by Django 4.2.9 on 2025-09-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0028_remove_zone_administrator_remove_zone_overseer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='zone', to='churches.zonename'),
        ),
    ]
