# Generated by Django 4.2.9 on 2025-09-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0029_alter_zone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_zone', to='churches.zone'),
        ),
    ]
