# Generated by Django 4.2.9 on 2025-09-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0030_alter_church_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assembly_zone', to='churches.zone'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
