# Generated by Django 4.2.9 on 2026-02-26 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churches', '0031_alter_church_zone_alter_zone_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('overseer', 'Overseer'), ('assistant', 'Assistant'), ('coordinator', 'Coordinator')], max_length=30)),
                ('appointed_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['name'], 'verbose_name': 'Assembly', 'verbose_name_plural': 'Assemblies'},
        ),
        migrations.RemoveField(
            model_name='zone',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='overseers',
        ),
        migrations.AddField(
            model_name='zone',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='zone',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='office_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='zone',
            name='office_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='zone',
            name='office_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['code'], name='churches_zo_code_1f41bc_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['is_active'], name='churches_zo_is_acti_ed5e98_idx'),
        ),
        migrations.AddField(
            model_name='zoneleadership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zoneleadership',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership', to='churches.zone'),
        ),
        migrations.AddIndex(
            model_name='zoneleadership',
            index=models.Index(fields=['zone', 'role'], name='churches_zo_zone_id_1ab2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='zoneleadership',
            index=models.Index(fields=['is_active'], name='churches_zo_is_acti_c0c999_idx'),
        ),
        migrations.AddConstraint(
            model_name='zoneleadership',
            constraint=models.UniqueConstraint(fields=('zone', 'user', 'role', 'appointed_at'), name='unique_zone_role_assignment'),
        ),
    ]
