# Generated by Django 4.2.9 on 2026-02-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0032_zoneleadership_alter_church_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
