# Generated by Django 4.2.9 on 2026-03-04 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0033_alter_zone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assemblies', to='churches.zone'),
        ),
    ]
