# Generated by Django 6.0.3 on 2026-06-15 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0035_region_regionleadership_delete_imageupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='churches.region'),
        ),
    ]
