# Generated by Django 6.0.3 on 2026-06-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0036_zone_region'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='unique_zone_name_per_region'),
        ),
    ]
