# Generated by Django 6.0.3 on 2026-06-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0037_zone_unique_zone_name_per_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
