# Generated by Django 6.0.3 on 2026-06-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0038_alter_zone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
