# Generated by Django 6.0.3 on 2026-06-15 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0039_zone_deleted_at_alter_zone_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionZoneCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='churches.region')),
            ],
        ),
    ]
