# Generated by Django 6.0.3 on 2026-06-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0040_regionzonecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True),
        ),
    ]
