# Generated by Django 6.0.3 on 2026-06-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0041_alter_zone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
