# Generated by Django 6.0.3 on 2026-06-19 16:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0042_alter_zone_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyMonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('new_members', models.PositiveIntegerField(default=0)),
                ('tithes_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remittance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('attendance', models.PositiveIntegerField(default=0)),
                ('average_attendance', models.PositiveIntegerField(default=0)),
                ('first_time_guests', models.PositiveIntegerField(default=0)),
                ('people_reached', models.PositiveIntegerField(default=0)),
                ('people_converted', models.PositiveIntegerField(default=0)),
                ('baptisms', models.PositiveIntegerField(default=0)),
                ('outreaches_conducted', models.PositiveIntegerField(default=0)),
                ('homecells_planted', models.PositiveIntegerField(default=0)),
                ('leaders_trained', models.PositiveIntegerField(default=0)),
                ('meetings_conducted', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_targets', to='churches.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monthly_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'assembly__name'],
                'indexes': [models.Index(fields=['assembly', 'year', 'month'], name='churches_as_assembl_7ced75_idx'), models.Index(fields=['status'], name='churches_as_status_e7a2e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('assembly', 'year', 'month'), name='unique_assembly_monthly_target')],
            },
        ),
        migrations.CreateModel(
            name='ChurchMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('board', 'Board'), ('deacons', 'Deacons'), ('elders', 'Elders'), ('pastors', 'Pastors'), ('workers', 'Workers'), ('youth', 'Youth'), ('prayer', 'Prayer'), ('general', 'General')], db_index=True, default='general', max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20)),
                ('mode', models.CharField(choices=[('in_person', 'In Person'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='in_person', max_length=20)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('online_link', models.URLField(blank=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('expected_attendance', models.PositiveIntegerField(default=0)),
                ('actual_attendance', models.PositiveIntegerField(default=0)),
                ('agenda', models.TextField(blank=True)),
                ('minutes_summary', models.TextField(blank=True)),
                ('decisions', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='churches.church')),
                ('chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_church_meetings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_church_meetings', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minuted_church_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
                'ordering': ['-starts_at', '-created_at'],
                'indexes': [models.Index(fields=['assembly', 'starts_at'], name='churches_ch_assembl_18e5e3_idx'), models.Index(fields=['meeting_type'], name='churches_ch_meeting_dab4d2_idx'), models.Index(fields=['status'], name='churches_ch_status_3054e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('outreach_date', models.DateField(db_index=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20)),
                ('outreach_team_size', models.PositiveIntegerField(default=0)),
                ('member_attendance', models.PositiveIntegerField(default=0)),
                ('total_people_reached', models.PositiveIntegerField(default=0)),
                ('total_people_converted', models.PositiveIntegerField(default=0)),
                ('total_new_members', models.PositiveIntegerField(default=0)),
                ('total_baptisms', models.PositiveIntegerField(default=0)),
                ('outreach_materials_distributed', models.PositiveIntegerField(default=0)),
                ('outreach_material_notes', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreaches', to='churches.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_outreaches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-outreach_date', '-created_at'],
                'indexes': [models.Index(fields=['assembly', 'outreach_date'], name='churches_ou_assembl_2d9818_idx'), models.Index(fields=['status'], name='churches_ou_status_5c866b_idx')],
            },
        ),
    ]
