# Generated by Django 6.0.3 on 2026-06-22 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churches", "0043_assemblymonthlytarget_churchmeeting_outreach"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AssemblyMonthlyTarget",
            new_name="Forecast",
        ),
        migrations.RenameIndex(
            model_name="forecast",
            old_name="churches_as_assembl_7ced75_idx",
            new_name="churches_fo_assembl_3d521d_idx",
        ),
        migrations.RenameIndex(
            model_name="forecast",
            old_name="churches_as_status_e7a2e8_idx",
            new_name="churches_fo_status_6a60cf_idx",
        ),
        migrations.RemoveConstraint(
            model_name="forecast",
            name="unique_assembly_monthly_target",
        ),
        migrations.AlterField(
            model_name="forecast",
            name="assembly",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="forecasts",
                to="churches.church",
            ),
        ),
        migrations.AlterField(
            model_name="forecast",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_forecasts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="forecast",
            constraint=models.UniqueConstraint(
                fields=("assembly", "year", "month"),
                name="unique_assembly_forecast",
            ),
        ),
    ]
