# Generated by Django 6.0.3 on 2026-06-24 14:41

import apps.churches.models.assembly
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0044_rename_forecast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='ISO currency code, e.g. USD, ZAR, NAD, ZWG', max_length=3)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assembly Currency',
                'verbose_name_plural': 'Assembly Currencies',
                'ordering': ['-is_primary', 'currency'],
            },
        ),
        migrations.AlterModelOptions(
            name='outreach',
            options={'ordering': ['-outreach_date', '-created_at'], 'verbose_name': 'Outreach', 'verbose_name_plural': 'Outreaches'},
        ),
        migrations.RemoveField(
            model_name='church',
            name='language',
        ),
        migrations.AddField(
            model_name='church',
            name='code',
            field=models.CharField(blank=True, help_text='Short assembly code, e.g. CFI-HRE-001', max_length=20),
        ),
        migrations.AddField(
            model_name='church',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='locale',
            field=models.CharField(blank=True, help_text='Locale used for formatting, e.g. en-ZW, en-ZA, en-NA', max_length=10),
        ),
        migrations.AddField(
            model_name='church',
            name='public_id',
            field=models.CharField(db_index=True, default=apps.churches.models.assembly.generate_public_id, editable=False, max_length=21),
        ),
        migrations.AlterField(
            model_name='church',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='church',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assemblies', to='churches.zone'),
        ),
        migrations.AlterField(
            model_name='regionleadership',
            name='role',
            field=models.CharField(choices=[('overseer', 'Overseer'), ('overseer_pa', 'Overseer PA'), ('region_moderator', 'Region Moderator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='regionleadership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['name'], name='churches_ch_name_ce9156_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['country_code'], name='churches_ch_country_21c444_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['zone'], name='churches_ch_zone_id_41d0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['status'], name='churches_ch_status_e5b1bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='regionleadership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('region', 'user', 'role'), name='unique_active_region_user_role'),
        ),
        migrations.AddField(
            model_name='assemblycurrency',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='churches.church'),
        ),
        migrations.AddConstraint(
            model_name='assemblycurrency',
            constraint=models.UniqueConstraint(fields=('assembly', 'currency'), name='unique_currency_per_assembly'),
        ),
        migrations.AddConstraint(
            model_name='assemblycurrency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('assembly',), name='unique_primary_currency_per_assembly'),
        ),
    ]
