# Generated by Django 6.0.3 on 2026-06-24 15:39

import apps.churches.models.assembly
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0045_assemblycurrency_alter_outreach_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionleadership',
            options={'verbose_name': 'Region Leadership', 'verbose_name_plural': 'Region Leadership'},
        ),
        migrations.RemoveConstraint(
            model_name='assemblycurrency',
            name='unique_currency_per_assembly',
        ),
        migrations.RemoveConstraint(
            model_name='assemblycurrency',
            name='unique_primary_currency_per_assembly',
        ),
        migrations.AlterField(
            model_name='church',
            name='public_id',
            field=models.CharField(db_index=True, default=apps.churches.models.assembly.generate_public_id, max_length=21),
        ),
    ]
