# Generated by Django 6.0.3 on 2026-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0046_alter_regionleadership_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assemblycurrency',
            constraint=models.UniqueConstraint(fields=('assembly', 'currency'), name='unique_currency_per_assembly'),
        ),
        migrations.AddConstraint(
            model_name='assemblycurrency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('assembly',), name='unique_primary_currency_per_assembly'),
        ),
    ]
