# Generated by Django 6.0.3 on 2026-06-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0047_assemblycurrency_unique_currency_per_assembly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='cover_image_position',
            field=models.CharField(default='center', max_length=20),
        ),
    ]
