# Generated by Django 6.0.3 on 2026-06-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0048_church_cover_image_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='church',
            name='status',
            field=models.CharField(blank=True, choices=[('closed', 'Closed'), ('open', 'Open'), ('merged', 'Merged'), ('suspended', 'Suspended')], default='open', max_length=10),
        ),
    ]
