# Generated by Django 6.0.3 on 2026-06-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0049_remove_church_is_active_alter_church_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
