# Generated by Django 6.0.3 on 2026-06-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0050_alter_church_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='code',
            field=models.CharField(blank=True, help_text='Short assembly code, e.g. CFI-EAZ-026', max_length=20),
        ),
    ]
