# Generated by Django 6.0.3 on 2026-09-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0051_alter_church_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionleadership',
            name='role',
            field=models.CharField(choices=[('regional_admin', 'Regional Admin'), ('overseer', 'Overseer'), ('overseer_pa', 'Overseer PA'), ('region_moderator', 'Region Moderator')], max_length=50),
        ),
    ]
