# Generated by Django 4.2.9 on 2025-04-15 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_ref', models.CharField(default='SDhH_Sz-XVTS', max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('platform', models.CharField(choices=[('database', 'Database'), ('academy', 'Academy')], default='database', max_length=20)),
                ('read_more_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
