# Generated by Django 4.2.9 on 2025-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='_ref',
            field=models.CharField(default='iGqVmI-yIME3', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
