# Generated by Django 4.2.9 on 2025-04-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_alter_announcement__ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='_ref',
        ),
        migrations.AddField(
            model_name='announcement',
            name='reference',
            field=models.CharField(default='vO-LJ-BWj8ts', max_length=50, unique=True),
        ),
    ]
