# Generated by Django 4.2.9 on 2025-04-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_remove_announcement__ref_announcement_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='reference',
            field=models.CharField(default='GZ5gNSUPbmoJ', max_length=50, unique=True),
        ),
    ]
