# Generated by Django 4.2.9 on 2025-04-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='reference',
            field=models.CharField(default='2KUix3PC1cml', max_length=50, unique=True),
        ),
    ]
