# Generated by Django 4.2.9 on 2025-05-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_alter_announcement_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='reference',
            field=models.CharField(default='C5RLlki2_n_t', max_length=50, unique=True),
        ),
    ]
