# Generated by Django 4.2.9 on 2025-05-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0033_alter_announcement_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='reference',
            field=models.CharField(default='3TkyXT24-qO0', max_length=50, unique=True),
        ),
    ]
