# Generated by Django 4.2.9 on 2025-05-07 17:58

import apps.announcements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0039_alter_announcement_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='reference',
            field=models.CharField(default=apps.announcements.models.generate_reference, max_length=50, unique=True),
        ),
    ]
