# Generated by Django 4.2.9 on 2025-04-12 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the external system (e.g. LMS, HR System)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the system')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to disable use of the system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External System',
                'verbose_name_plural': 'External Systems',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_id', models.CharField(max_length=32, unique=True, verbose_name='Student/Staff/External ID')),
                ('integration_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('other', 'Other')], default='other', max_length=10)),
                ('meta_data', models.JSONField(blank=True, default=dict, help_text='Optional data from the external system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrations', to='integrations.externalsystem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'unique_together': {('user', 'system')},
            },
        ),
    ]
