# Generated by Django 4.2.9 on 2025-04-18 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalSystem',
            new_name='IntegrationProvider',
        ),
        migrations.RenameField(
            model_name='integration',
            old_name='system',
            new_name='integration_provider',
        ),
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('user', 'integration_provider')},
        ),
        migrations.AlterField(
            model_name='integration',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, help_text='Optional data from the integration provider'),
        ),
    ]
