# Generated by Django 4.2.9 on 2025-04-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_rename_externalsystem_integrationprovider_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationprovider',
            options={'ordering': ['name'], 'verbose_name': 'Integration Provider', 'verbose_name_plural': 'Integration Providers'},
        ),
    ]
