# Generated by Django 4.2.3 on 2023-11-13 16:25

import apps.office.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0007_church_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('mode', models.CharField(blank=True, choices=[('in-person', 'In Person'), ('virtual', 'Virtual')], default='in-person', max_length=255)),
                ('platform', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('zoom', 'Zoom')], max_length=255)),
                ('timestamp_start', models.DateField()),
                ('timestamp_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_branch', to='churches.church')),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.office.utils.meeting_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes_branch', to='churches.church')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_minutes', to='office.meeting')),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
                'ordering': ['-created_at'],
            },
        ),
    ]
