# Generated by Django 4.2.3 on 2023-11-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minutes',
            options={'ordering': ['-created_at'], 'verbose_name': 'minute', 'verbose_name_plural': 'minutes'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='timestamp_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='timestamp_start',
            field=models.DateTimeField(),
        ),
    ]
