# Generated by Django 4.2.3 on 2023-11-15 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_minutes_options_alter_meeting_timestamp_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='office.meeting'),
        ),
    ]
