# Generated by Django 4.2.3 on 2023-11-15 11:44

import apps.office.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0007_church_currency'),
        ('office', '0003_alter_minutes_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.office.models.strategy_file_path)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('color_id', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circular_branch', to='churches.church')),
            ],
            options={
                'verbose_name': 'circular',
                'verbose_name_plural': 'circular',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Curicular',
        ),
        migrations.AddField(
            model_name='meeting',
            name='color_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
