# Generated by Django 5.0.1 on 2024-01-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_document_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='attachment',
            new_name='uploaded_file',
        ),
        migrations.RenameField(
            model_name='minutes',
            old_name='attachment',
            new_name='uploaded_file',
        ),
    ]
