# Generated by Django 5.0.1 on 2024-01-14 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0012_alter_church_status'),
        ('office', '0008_rename_attachment_document_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document', to='churches.church'),
        ),
    ]
