# Generated by Django 5.0.1 on 2024-01-15 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_alter_document_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_file',
            new_name='uploaded_document',
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, choices=[('strategy', 'Strategy'), ('president', 'President Circular'), ('general', 'General Overseer Circular'), ('national', 'National Overseer Circular'), ('secretary', 'Secretary General Circular')], max_length=255),
        ),
    ]
