# Generated by Django 5.0.1 on 2024-01-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_rename_uploaded_file_document_uploaded_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='moderated_by',
        ),
    ]
