# Generated by Django 5.0.1 on 2024-01-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_document_moderated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='timestamp_end',
            new_name='meeting_end_time',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='timestamp_start',
            new_name='meeting_start_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='category',
            field=models.CharField(blank=True, choices=[('board', 'Board'), ('deacons', 'Deacons'), ('elders', 'Elders'), ('workers', 'Workers'), ('youth', 'Youth')], max_length=255),
        ),
    ]
