# Generated by Django 5.0.1 on 2024-01-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_rename_timestamp_end_meeting_meeting_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(blank=True, choices=[('board', 'Board'), ('deacons', 'Deacons'), ('elders', 'Elders'), ('pastors', 'Pastors'), ('workers', 'Workers'), ('youth', 'Youth')], max_length=255),
        ),
    ]
