# Generated by Django 5.0.1 on 2024-01-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_meeting_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='platform',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('zoom', 'Zoom')], max_length=255),
        ),
    ]
