# Generated by Django 4.2.9 on 2024-02-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0012_alter_church_status'),
        ('office', '0019_remove_strategy_branch_strategy_assembly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='minutes',
            name='branch',
        ),
        migrations.AddField(
            model_name='meeting',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_assembly', to='churches.church'),
        ),
        migrations.AddField(
            model_name='minutes',
            name='assembly',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_minutes', to='churches.church'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='platform',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('meet', 'Google Meet'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('zoom', 'Zoom')], default='zoom', max_length=255),
        ),
    ]
