# Generated by Django 4.2.9 on 2024-02-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0020_remove_meeting_branch_remove_minutes_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='category',
            field=models.CharField(blank=True, choices=[('president', 'President Circular'), ('general', 'General Overseer Circular'), ('national', 'National Overseer Circular'), ('secretary', 'Secretary General Circular')], max_length=255),
        ),
    ]
