# Generated by Django 4.2.1 on 2023-05-27 20:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tithes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('offering', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pledges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fundraising', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('thanksgiving', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('funds_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='church.church')),
            ],
            options={
                'verbose_name': 'finance',
                'verbose_name_plural': 'finances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=255)),
                ('invoice_date', models.DateField()),
                ('item', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('expense_type', models.CharField(choices=[('amenities', 'Amenities'), ('conference', 'Conference'), ('decor', 'Decor'), ('fellowship', 'Fellowship'), ('fixed', 'Fixed'), ('humanitarian', 'Humanitarian'), ('office', 'Office'), ('other', 'Other'), ('outreach', 'Outreach'), ('repair', 'Repair'), ('travel', 'Travel'), ('wages', 'Wages')], max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure', to='church.church')),
            ],
            options={
                'verbose_name': 'expenditure',
                'verbose_name_plural': 'expenditure',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('asset_group', models.CharField(choices=[('building', 'Building'), ('other', 'Other'), ('instrument', 'Instrument'), ('vehicle', 'Vehicle')], max_length=255)),
                ('description', models.TextField()),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valuation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Old', 'Old'), ('Not working', 'Not Working')], max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/assets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='church.church')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
