# Generated by Django 4.2.1 on 2023-06-11 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_group',
            field=models.CharField(choices=[('Building', 'Building'), ('Other', 'Other'), ('Instrument', 'Instrument'), ('Vehicle', 'Vehicle')], max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Old', 'Old'), ('Not Working', 'Not Working')], max_length=255),
        ),
    ]
