# Generated by Django 4.2.1 on 2023-06-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_remove_demographics_church_remove_member_church_and_more'),
        ('finance', '0003_rename_description_expenditure_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='church.church'),
        ),
    ]
