# Generated by Django 4.2.1 on 2023-06-29 21:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_income_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
