# Generated by Django 4.2.1 on 2023-07-05 23:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_church_pastor'),
        ('finance', '0005_alter_asset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euid', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('basic', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('benefits', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='church.church')),
            ],
            options={
                'verbose_name': 'payroll',
                'verbose_name_plural': 'payrolls',
                'ordering': ['-created'],
            },
        ),
    ]
