# Generated by Django 4.2.1 on 2023-07-05 14:15

import apps.resources.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'directory',
                'verbose_name_plural': 'directories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('images', 'Images'), ('documents', 'Documents'), ('videos', 'Videos'), ('other', 'Other')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.resources.models.storageURL)),
                ('file', models.FileField(upload_to='uploads/', validators=[apps.resources.models.validate_non_image_file])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory', to='resources.directory')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='directory',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='file_dir', to='resources.file'),
        ),
        migrations.AddField(
            model_name='directory',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='image_dir', to='resources.file'),
        ),
    ]
