# Generated by Django 4.2.3 on 2023-12-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='image',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_image_fallback',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
