# Generated by Django 4.2.9 on 2025-03-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
