# Generated by Django 4.2.9 on 2025-03-15 18:37

import apps.core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_termsandconditions_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Attendance', 'Attendance'), ('Authentication', 'Authentication'), ('Changelog', 'Changelog'), ('Demographics', 'Demographics'), ('Finance', 'Finance'), ('General', 'General'), ('Strategy', 'Strategy'), ('Templates', 'Templates'), ('Updates', 'Updates')], default='General', max_length=255)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.core.utils.blog_image_url)),
                ('views', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_author', to=settings.AUTH_USER_MODEL)),
                ('read_by', models.ManyToManyField(blank=True, related_name='blog_post_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
