# Generated by Django 4.2.9 on 2025-03-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='body',
        ),
    ]
