# Generated by Django 4.2.9 on 2025-03-20 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_rename_description_blog_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('General', 'General'), ('API', 'API'), ('User Guide', 'User Guide'), ('Technical', 'Technical')], default='General', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documentation',
                'verbose_name_plural': 'Documentation',
                'ordering': ['-created_at'],
            },
        ),
    ]
