# Generated by Django 4.2.9 on 2025-05-23 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_blog_subtitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermsAndConditions',
            new_name='TOS',
        ),
        migrations.RenameModel(
            old_name='UserTermsAcceptance',
            new_name='TOSAcceptance',
        ),
        migrations.AlterModelOptions(
            name='tos',
            options={'verbose_name': 'Terms of Service', 'verbose_name_plural': 'Terms of Service'},
        ),
        migrations.AlterModelTable(
            name='tos',
            table='apps_core_termsandconditions',
        ),
    ]
