# Generated by Django 4.2.3 on 2023-07-06 11:59

import cloudinary.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0002_rename_desc_church_description_alter_church_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euid', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('basic', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('benefits', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='churches.church')),
            ],
            options={
                'verbose_name': 'payroll',
                'verbose_name_plural': 'payrolls',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tithes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('offering', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('pledges', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('fundraising', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('thanksgiving', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('funds_received', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='churches.church')),
            ],
            options={
                'verbose_name': 'finance',
                'verbose_name_plural': 'finances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=255)),
                ('invoice_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('expense_type', models.CharField(choices=[('amenities', 'Amenities'), ('conference', 'Conference'), ('decor', 'Decor'), ('fellowship', 'Fellowship'), ('fixed', 'Fixed'), ('humanitarian', 'Humanitarian'), ('office', 'Office'), ('other', 'Other'), ('outreach', 'Outreach'), ('repair', 'Repair'), ('travel', 'Travel'), ('wages', 'Wages')], max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure', to='churches.church')),
            ],
            options={
                'verbose_name': 'expenditure',
                'verbose_name_plural': 'expenditure',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purchase_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('asset_group', models.CharField(choices=[('Building', 'Building'), ('Other', 'Other'), ('Instrument', 'Instrument'), ('Vehicle', 'Vehicle')], max_length=255)),
                ('description', models.TextField()),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('valuation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Old', 'Old'), ('Not Working', 'Not Working')], max_length=255)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='churches.church')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
