# Generated by Django 4.2.3 on 2023-09-03 12:55

import apps.bookkeeper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='receipt',
            field=models.FileField(null=True, upload_to=apps.bookkeeper.models.receipt_file_path),
        ),
        migrations.AddField(
            model_name='income',
            name='bank_statement',
            field=models.FileField(null=True, upload_to=apps.bookkeeper.models.bank_statement_file_path),
        ),
    ]
