# Generated by Django 4.2.3 on 2023-09-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0002_expenditure_receipt_income_bank_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='finance/receipts/'),
        ),
        migrations.AlterField(
            model_name='income',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='finance/statements/'),
        ),
    ]
