# Generated by Django 4.2.3 on 2023-10-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0004_alter_expenditure_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='receipt',
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='expense_type',
            field=models.CharField(choices=[('Amenities', 'Amenities'), ('Conference', 'Conference'), ('Decor', 'Decor'), ('Fellowship', 'Fellowship'), ('Fixed', 'Fixed'), ('Hotel Bookings', 'Hotel Bookings'), ('Humanitarian', 'Humanitarian'), ('Office', 'Office'), ('Other', 'Other'), ('Outreach', 'Outreach'), ('Repair', 'Repair'), ('Travel', 'Travel'), ('Wages', 'Wages')], max_length=255),
        ),
    ]
