# Generated by Django 4.2.3 on 2023-10-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0005_remove_expenditure_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
