# Generated by Django 4.2.3 on 2023-10-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0006_income_entry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-created_at'], 'verbose_name': 'income', 'verbose_name_plural': 'income'},
        ),
    ]
