# Generated by Django 4.2.3 on 2023-10-12 14:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0008_alter_asset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='finance/assets/'),
        ),
    ]
