# Generated by Django 4.2.3 on 2023-12-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_alter_kindred_guardian'),
        ('bookkeeper', '0008_alter_fixedexpenditure_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['timestamp'], 'verbose_name': 'income', 'verbose_name_plural': 'income'},
        ),
        migrations.AlterField(
            model_name='tithe',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tither', to='people.member'),
        ),
    ]
