# Generated by Django 4.2.3 on 2023-12-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0009_alter_income_options_alter_tithe_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
