# Generated by Django 4.2.3 on 2023-10-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0009_expenditure_receipt_alter_asset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='finance/expenditure/'),
        ),
    ]
