# Generated by Django 4.2.3 on 2023-10-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0010_alter_expenditure_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='finance/expenditure/'),
        ),
    ]
