# Generated by Django 4.2.3 on 2023-10-16 11:33

import apps.bookkeeper.utils
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0007_church_currency'),
        ('people', '0008_attendanceregister_created_at_and_more'),
        ('bookkeeper', '0012_alter_expenditure_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='statement',
            field=models.FileField(blank=True, null=True, upload_to=apps.bookkeeper.utils.bank_statement_path),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.bookkeeper.utils.asset_image_path),
        ),
        migrations.CreateModel(
            name='Tithes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('EFT', 'EFT'), ('Other', 'Other')], default='Bank', max_length=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=apps.bookkeeper.utils.tithe_receipt_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tithe_branch', to='churches.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tither', to='people.member')),
            ],
            options={
                'verbose_name': 'tithe',
                'verbose_name_plural': 'tithes',
                'ordering': ['-created_at'],
            },
        ),
    ]
