# Generated by Django 4.2.3 on 2023-12-06 12:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookkeeper', '0013_remittance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remittance',
            name='has_shortfall',
        ),
        migrations.AlterField(
            model_name='remittance',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittance_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RemitShortfallPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('timestamp', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortfall_payments', to='bookkeeper.remittance')),
            ],
            options={
                'verbose_name': 'Shortfall Payment',
                'verbose_name_plural': 'Shortfall Payments',
                'ordering': ['timestamp'],
            },
        ),
    ]
