# Generated by Django 4.2.3 on 2023-10-16 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0013_income_statement_alter_asset_image_tithes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tithes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
