# Generated by Django 4.2.3 on 2023-10-19 17:39

import apps.bookkeeper.utils
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_status'),
        ('churches', '0007_church_currency'),
        ('people', '0015_tally'),
        ('bookkeeper', '0013_income_statement_alter_asset_image_tithes'),
    ]

    operations = [

        migrations.AlterField(
            model_name='expenditure',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=apps.bookkeeper.utils.expenditure_receipt_path),
        ),
        
    ]
