# Generated by Django 4.2.3 on 2023-10-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_attendanceregister_created_at_and_more'),
        ('churches', '0007_church_currency'),
        ('bookkeeper', '0014_alter_tithes_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tithes',
            new_name='Tithe',
        ),
    ]
