# Generated by Django 4.2.3 on 2023-10-18 20:05

import apps.bookkeeper.utils
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churches', '0007_church_currency'),
        ('people', '0014_rename_repented_hcattendance_altar_call'),
        ('bookkeeper', '0014_fixedexpenditure_pledge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tithe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('EFT', 'EFT'), ('Other', 'Other')], default='Bank', max_length=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=apps.bookkeeper.utils.tithe_receipt_path)),
                ('timestamp', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tithe_branch', to='churches.church')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tithe_editor', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tither', to='people.member')),
            ],
            options={
                'verbose_name': 'tithe',
                'verbose_name_plural': 'tithes',
                'ordering': ['-created_at'],
            },
        ),
    ]
