# Generated by Django 4.2.3 on 2023-10-16 13:49

import apps.bookkeeper.utils
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0007_church_currency'),
        ('people', '0008_attendanceregister_created_at_and_more'),
        ('projects', '0002_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookkeeper', '0015_rename_tithes_tithe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('EFT', 'EFT'), ('Other', 'Other')], default='Bank', max_length=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=apps.bookkeeper.utils.pledge_receipt_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_branch', to='churches.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledger', to='people.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_pledge', to='projects.project')),
            ],
            options={
                'verbose_name': 'pledge',
                'verbose_name_plural': 'pledges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FixedExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('central_account_remittance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('rent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('water', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('telephone', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('internet', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('security', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('electricity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('receipt', models.FileField(upload_to=apps.bookkeeper.utils.expenditure_receipt_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_expenditure', to='churches.church')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_expenditure_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fixed Expenditure',
                'verbose_name_plural': 'Fixed Expenditures',
                'ordering': ['-created_at'],
            },
        ),
    ]
