# Generated by Django 4.2.3 on 2023-12-06 12:15

import apps.bookkeeper.utils
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0007_church_currency'),
        ('bookkeeper', '0015_remitshortfallpayment_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortfallPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.bookkeeper.utils.shortfall_receipt_path)),
                ('timestamp', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortfall_branch', to='churches.church')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortfall_payments', to='bookkeeper.remittance')),
            ],
            options={
                'verbose_name': 'Shortfall Payment',
                'verbose_name_plural': 'Shortfall Payments',
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='RemitShortfallPayment',
        ),
    ]
