# Generated by Django 4.2.3 on 2023-12-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0016_shortfallpayment_delete_remitshortfallpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortfallpayment',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Shortfall Payment', 'verbose_name_plural': 'Shortfall Payments'},
        ),
    ]
