# Generated by Django 4.2.3 on 2023-10-16 14:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0016_pledge_fixedexpenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpenditure',
            name='fuel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='fixedexpenditure',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
