# Generated by Django 4.2.3 on 2023-10-16 16:07

import apps.bookkeeper.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0017_fixedexpenditure_fuel_fixedexpenditure_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=apps.bookkeeper.utils.expenditure_receipt_path),
        ),
        migrations.AlterField(
            model_name='fixedexpenditure',
            name='receipt',
            field=models.FileField(blank=True, upload_to=apps.bookkeeper.utils.fixed_expenditure_receipt_path),
        ),
    ]
