# Generated by Django 4.2.3 on 2023-12-14 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookkeeper', '0017_alter_shortfallpayment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortfallpayment',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortfall_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortfallpayment',
            name='payment_method',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('EFT', 'EFT'), ('Other', 'Other')], default='Bank', max_length=10),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittance_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
