# Generated by Django 4.2.3 on 2023-10-16 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0018_alter_expenditure_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
