# Generated by Django 4.2.3 on 2023-12-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0018_shortfallpayment_editor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='period',
            field=models.DateField(null=True),
        ),
    ]
