# Generated by Django 4.2.3 on 2023-10-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0019_pledge_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='entry_date',
            new_name='timestamp',
        ),
    ]
