# Generated by Django 4.2.3 on 2023-12-15 00:07

import apps.bookkeeper.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0020_rename_name_asset_asset_name_asset_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.bookkeeper.utils.asset_image_path),
        ),
    ]
