# Generated by Django 4.2.3 on 2023-10-17 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookkeeper', '0020_rename_entry_date_income_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tithe',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tithe_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tithe',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
