# Generated by Django 4.2.3 on 2023-10-17 15:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0021_tithe_editor_tithe_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpenditure',
            name='wages',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
