# Generated by Django 4.2.9 on 2024-03-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0022_rename_asset_group_asset_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedexpenditure',
            name='central_account_remittance',
        ),
        migrations.RemoveField(
            model_name='income',
            name='remittance',
        ),
    ]
