# Generated by Django 4.2.3 on 2023-10-17 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0022_fixedexpenditure_wages'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpenditure',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
