# Generated by Django 4.2.9 on 2024-04-28 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookkeeper', '0023_remove_fixedexpenditure_central_account_remittance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedexpenditure',
            name='editor',
        ),
        migrations.AddField(
            model_name='fixedexpenditure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_expenditure_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
