# Generated by Django 4.2.9 on 2024-04-28 20:11

import apps.bookkeeper.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0024_remove_fixedexpenditure_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedexpenditure',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=apps.bookkeeper.utils.fixed_expenditure_receipt_path),
        ),
    ]
