# Generated by Django 4.2.9 on 2024-04-29 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churches', '0012_alter_church_status'),
        ('people', '0026_alter_attendance_options_alter_homecell_options_and_more'),
        ('bookkeeper', '0026_rename_branch_fixedexpenditure_assembly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedexpenditure',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='tithe',
            name='editor',
        ),
        migrations.AddField(
            model_name='tithe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tithe_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fixedexpenditure',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_expenditure', to='churches.church'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('eft', 'EFT'), ('mobile', 'Mobile'), ('other', 'Other')], default='bank', max_length=10),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('eft', 'EFT'), ('mobile', 'Mobile'), ('other', 'Other')], default='bank', max_length=10),
        ),
        migrations.AlterField(
            model_name='shortfallpayment',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('eft', 'EFT'), ('mobile', 'Mobile'), ('other', 'Other')], default='bank', max_length=10),
        ),
        migrations.AlterField(
            model_name='tithe',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly', to='churches.church'),
        ),
        migrations.AlterField(
            model_name='tithe',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tither', to='people.member'),
        ),
        migrations.AlterField(
            model_name='tithe',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('eft', 'EFT'), ('mobile', 'Mobile'), ('other', 'Other')], default='bank', max_length=10),
        ),
    ]
