# Generated by Django 4.2.9 on 2024-05-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0028_income_donations_alter_expenditure_expense_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='expense_type',
            new_name='category',
        ),
    ]
