# Generated by Django 4.2.9 on 2024-05-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0030_expenditure_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='church',
            new_name='assembly',
        ),
    ]
