# Generated by Django 4.2.9 on 2024-08-25 21:10

import apps.bookkeeper.utils
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0031_rename_church_expenditure_assembly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='church',
            new_name='assembly',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=apps.bookkeeper.utils.asset_images_path)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookkeeper.asset')),
            ],
            options={
                'verbose_name': 'Asset Image',
                'verbose_name_plural': 'Asset Images',
            },
        ),
    ]
