# Generated by Django 4.2.9 on 2024-08-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0034_rename_valuation_asset_current_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('building', 'Building'), ('instrument', 'Instrument'), ('vehicle', 'Vehicle'), ('furniture', 'Furniture'), ('electronics', 'Electronics'), ('machinery', 'Machinery'), ('software', 'Software'), ('land', 'Land'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('old', 'Old'), ('not_working', 'Not Working')], max_length=20),
        ),
    ]
