# Generated by Django 4.2.9 on 2024-08-25 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0036_alter_asset_asset_id_alter_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_id',
        ),
    ]
