# Generated by Django 4.2.9 on 2024-10-09 05:50

import apps.bookkeeper.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0037_remove_asset_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpenditure',
            name='remittance_receipt',
            field=models.FileField(blank=True, null=True, upload_to=apps.bookkeeper.utils.remittance_receipt_path),
        ),
    ]
