# Generated by Django 4.2.9 on 2024-10-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0038_fixedexpenditure_remittance_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpenditure',
            name='is_remittance_payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
