# Generated by Django 4.2.9 on 2024-10-09 18:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0039_fixedexpenditure_is_remittance_payment_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpenditure',
            name='remittance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
