# Generated by Django 4.2.9 on 2024-10-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0040_fixedexpenditure_remittance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedexpenditure',
            old_name='is_remittance_payment_verified',
            new_name='is_remittance_verified',
        ),
    ]
