# Generated by Django 4.2.9 on 2024-10-10 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookkeeper', '0041_rename_is_remittance_payment_verified_fixedexpenditure_is_remittance_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpenditure',
            name='remittance_moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remittance_moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
