# Generated by Django 4.2.9 on 2024-10-12 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookkeeper', '0042_fixedexpenditure_remittance_moderator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['item_name'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='purchase_price',
            new_name='acquisition_cost',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='purchase_date',
            new_name='acquisition_date',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='serial_number',
            new_name='item_code',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='current_value',
            new_name='residual',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='quantity',
            new_name='units',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='supplier',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
