# Generated by Django 4.2.9 on 2024-10-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0043_alter_asset_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
    ]
