# Generated by Django 4.2.9 on 2024-10-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0044_remove_asset_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
