# Generated by Django 4.2.9 on 2025-05-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0046_rename_sum_income_total_income_income_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='income',
            name='expenses',
        ),
    ]
