# Generated by Django 4.2.9 on 2025-05-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0047_remove_income_balance_remove_income_expenses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedexpenditure',
            options={'ordering': ['timestamp'], 'verbose_name': 'Fixed Expense', 'verbose_name_plural': 'Fixed Expenses'},
        ),
        migrations.AddField(
            model_name='tithe',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tithe',
            name='reference_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
