# Generated by Django 4.2.9 on 2025-06-14 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0023_rename_iso_country_code_church_country_code'),
        ('bookkeeper', '0048_alter_fixedexpenditure_options_tithe_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFinanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('gross_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tithes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('book_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_snapshots', to='churches.church')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('church', 'year', 'month')},
            },
        ),
    ]
