# Generated by Django 4.2.9 on 2025-06-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0049_monthlyfinancesnapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tithe',
            old_name='branch',
            new_name='assembly',
        ),
    ]
