# Generated by Django 4.2.9 on 2025-08-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0051_alter_pledge_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tithe',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
