# Generated by Django 4.2.9 on 2025-08-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0052_tithe_is_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='tithe',
            name='trash_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
