# Generated by Django 4.2.9 on 2025-09-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('bookkeeper', '0054_fixedexpenditure_report_income_report_tithe_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedexpenditure',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenditure_set', to='reports.unifiedreport'),
        ),
        migrations.AlterField(
            model_name='income',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='reports.unifiedreport'),
        ),
        migrations.AlterField(
            model_name='tithe',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='reports.unifiedreport'),
        ),
    ]
