# Generated by Django 4.2.9 on 2026-02-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_rename_unifiedreport_assemblyreport_and_more'),
        ('bookkeeper', '0055_alter_fixedexpenditure_report_alter_income_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_expenditure_set', to='reports.assemblyreport'),
        ),
    ]
