# Generated by Django 4.2.9 on 2026-02-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_rename_unifiedreport_assemblyreport_and_more'),
        ('churches', '0033_alter_zone_code'),
        ('bookkeeper', '0056_expenditure_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateField()),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churches.church')),
            ],
            options={
                'verbose_name': 'fixed expense',
                'verbose_name_plural': 'fixed expenses',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FixedExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_global', models.BooleanField(default=True)),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='churches.church')),
            ],
            options={
                'verbose_name': 'fixed expense type',
                'verbose_name_plural': 'fixed expenses',
            },
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='church',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='member',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='project',
        ),
        migrations.RemoveField(
            model_name='remittance',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='remittance',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='shortfallpayment',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='shortfallpayment',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='shortfallpayment',
            name='remittance',
        ),
        migrations.DeleteModel(
            name='BankStatement',
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
        migrations.DeleteModel(
            name='Pledge',
        ),
        migrations.DeleteModel(
            name='Remittance',
        ),
        migrations.DeleteModel(
            name='ShortfallPayment',
        ),
        migrations.AddField(
            model_name='fixedexpense',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeper.fixedexpensetype'),
        ),
        migrations.AddField(
            model_name='fixedexpense',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.assemblyreport'),
        ),
        migrations.AlterUniqueTogether(
            name='fixedexpense',
            unique_together={('report', 'expense_type')},
        ),
    ]
