# Generated by Django 4.2.9 on 2026-02-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_rename_unifiedreport_assemblyreport_and_more'),
        ('churches', '0033_alter_zone_code'),
        ('bookkeeper', '0057_fixedexpense_fixedexpensetype_remove_payroll_church_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FixedExpense',
            new_name='Overhead',
        ),
        migrations.RenameModel(
            old_name='FixedExpenseType',
            new_name='OverheadType',
        ),
        migrations.AlterModelOptions(
            name='overhead',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Overhead', 'verbose_name_plural': 'Overheads'},
        ),
        migrations.AlterModelOptions(
            name='overheadtype',
            options={'verbose_name': 'Overhead type', 'verbose_name_plural': 'Overhead types'},
        ),
    ]
