# Generated by Django 4.2.9 on 2026-02-27 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0033_alter_zone_code'),
        ('reports', '0006_rename_unifiedreport_assemblyreport_and_more'),
        ('bookkeeper', '0058_rename_fixedexpense_overhead_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overhead',
            options={},
        ),
        migrations.AlterModelOptions(
            name='overheadtype',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='overhead',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='overhead',
            name='overhead_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='overheads', to='bookkeeper.overheadtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overheadtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='overheadtype',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='overhead',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overheads', to='churches.church'),
        ),
        migrations.AlterField(
            model_name='overhead',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overheads', to='reports.assemblyreport'),
        ),
        migrations.AlterField(
            model_name='overheadtype',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overhead_types', to='churches.church'),
        ),
        migrations.AddIndex(
            model_name='overhead',
            index=models.Index(fields=['assembly'], name='bookkeeper__assembl_688036_idx'),
        ),
        migrations.AddIndex(
            model_name='overhead',
            index=models.Index(fields=['report'], name='bookkeeper__report__179d4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='overhead',
            constraint=models.UniqueConstraint(fields=('report', 'overhead_type'), name='unique_report_overhead_type'),
        ),
        migrations.AddConstraint(
            model_name='overheadtype',
            constraint=models.UniqueConstraint(fields=('assembly', 'name'), name='unique_overhead_type_per_assembly'),
        ),
        migrations.RemoveField(
            model_name='overhead',
            name='expense_type',
        ),
        migrations.RemoveField(
            model_name='overhead',
            name='timestamp',
        ),
    ]
