# Generated by Django 4.2.9 on 2026-02-28 22:14

import apps.bookkeeper.utils
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0033_alter_zone_code'),
        ('reports', '0006_rename_unifiedreport_assemblyreport_and_more'),
        ('bookkeeper', '0060_alter_overhead_report_financialauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_standard', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churches.church')),
            ],
            options={
                'unique_together': {('church', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('timestamp', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement', models.FileField(blank=True, null=True, upload_to=apps.bookkeeper.utils.bank_statement_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenues', to='bookkeeper.revenuecategory')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churches.church')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='reports.assemblyreport')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['church', 'timestamp'], name='bookkeeper__church__9b636c_idx')],
            },
        ),
    ]
