# Generated by Django 4.2.9 on 2026-03-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0061_revenuecategory_revenue'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='revenue',
            name='bookkeeper__church__9b636c_idx',
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='church',
            new_name='assembly',
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['assembly', 'timestamp'], name='bookkeeper__assembl_ffe026_idx'),
        ),
    ]
