# Generated by Django 4.2.9 on 2026-03-03 14:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0033_alter_zone_code'),
        ('reports', '0011_remove_assemblyreport_unique_assembly_report_period_and_more'),
        ('bookkeeper', '0062_remove_revenue_bookkeeper__church__9b636c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overhead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overhead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='overhead',
            name='timestamp',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overhead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='overhead',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='overhead',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churches.church'),
        ),
        migrations.AlterField(
            model_name='overhead',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='reports.assemblyreport'),
        ),
    ]
