# Generated by Django 4.2.9 on 2026-03-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0063_overhead_created_at_overhead_notes_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='revenue',
            name='bookkeeper__assembl_ffe026_idx',
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['assembly'], name='bookkeeper__assembl_3f103a_idx'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['report'], name='bookkeeper__report__a43f26_idx'),
        ),
        migrations.AddConstraint(
            model_name='revenue',
            constraint=models.UniqueConstraint(fields=('report', 'category'), name='unique_report_category'),
        ),
    ]
