# Generated by Django 4.2.9 on 2026-03-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0033_alter_zone_code'),
        ('bookkeeper', '0064_remove_revenue_bookkeeper__assembl_ffe026_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenuecategory',
            old_name='church',
            new_name='assembly',
        ),
        migrations.AlterUniqueTogether(
            name='revenuecategory',
            unique_together={('assembly', 'name')},
        ),
    ]
