# Generated by Django 4.2.9 on 2026-03-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0065_rename_church_revenuecategory_assembly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overheadtype',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
