# Generated by Django 4.2.9 on 2026-03-04 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0059_remove_attendance_unique_service_attendance_and_more'),
        ('churches', '0033_alter_zone_code'),
        ('bookkeeper', '0066_alter_overheadtype_is_global'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tithe',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Tithe', 'verbose_name_plural': 'Tithes'},
        ),
        migrations.RemoveField(
            model_name='tithe',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='tithe',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churches.church'),
        ),
        migrations.AlterField(
            model_name='tithe',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tithes', to='people.member'),
        ),
        migrations.AlterField(
            model_name='tithe',
            name='timestamp',
            field=models.DateField(db_index=True),
        ),
    ]
