# Generated by Django 6.0.3 on 2026-04-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0067_alter_tithe_options_remove_tithe_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tithe',
            name='payment_method',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Mobile Money', 'Mobile Money'), ('Other', 'Other')], default='Bank', max_length=26),
        ),
    ]
