# Generated by Django 6.0.3 on 2026-04-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0068_alter_tithe_payment_method'),
        ('churches', '0034_alter_church_zone'),
        ('people', '0063_delete_uploadsession'),
        ('reports', '0016_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenditure',
            options={'ordering': ['-timestamp', '-invoice_date'], 'verbose_name': 'Expenditure', 'verbose_name_plural': 'Expenditure'},
        ),
        migrations.AddField(
            model_name='expenditure',
            name='timestamp',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='tithe',
            constraint=models.UniqueConstraint(fields=('report', 'member'), name='unique_report_member_tithe'),
        ),
    ]
