# Generated by Django 6.0.3 on 2026-08-12 15:13

import django.db.models.deletion
import django.utils.timezone
import re
import unicodedata
from django.conf import settings
from django.db import migrations, models


REVENUE_STANDARDS = [
    ("Donations & Gifts", "Giving"),
    ("Fundraising", "Giving"),
    ("Grants & Sponsorships", "External Support"),
    ("Asset Sales", "Asset Proceeds"),
    ("Interest & Investment Income", "Investment Income"),
    ("Rental Income", "Property Income"),
    ("Ministry & Event Income", "Ministry Income"),
    ("Other Revenue", "Other Revenue"),
]

OVERHEAD_STANDARDS = [
    ("Facilities & Utilities", "Facilities"),
    ("Staffing & Payroll", "People"),
    ("Administration & Office", "Administration"),
    ("Transport & Travel", "Operations"),
    ("Communications & Technology", "Operations"),
    ("Insurance & Compliance", "Governance"),
    ("Maintenance & Repairs", "Facilities"),
    ("Ministry Operations", "Ministry"),
    ("Bank & Professional Fees", "Administration"),
    ("Other Operating Expenses", "Other Operating Expenses"),
]


def normalize(value):
    value = unicodedata.normalize("NFKD", str(value or "")).casefold().strip()
    value = "".join(character for character in value if not unicodedata.combining(character))
    tokens = []
    for token in re.findall(r"[a-z0-9]+", value):
        if len(token) > 4 and token.endswith("ies"):
            token = f"{token[:-3]}y"
        elif len(token) > 4 and token.endswith("ses"):
            token = token[:-2]
        elif len(token) > 3 and token.endswith("s") and not token.endswith("ss"):
            token = token[:-1]
        tokens.append(token)
    return " ".join(tokens)


def populate_category_metadata(apps, schema_editor):
    RevenueCategory = apps.get_model("bookkeeper", "RevenueCategory")
    OverheadType = apps.get_model("bookkeeper", "OverheadType")

    seen_revenue = set()

    for category in RevenueCategory.objects.order_by("pk"):
        key = (category.assembly_id, normalize(category.name))
        normalized_name = key[1]

        if key in seen_revenue:
            normalized_name = f"{normalized_name} legacy {category.pk}"

        seen_revenue.add(key)

        category.normalized_name = normalized_name

        # Scope must agree with the constraints added later:
        # - assembly=None means a global/standard category
        # - assembly set means an assembly-specific custom category
        category.is_standard = category.assembly_id is None
        category.needs_review = category.assembly_id is not None

        category.save(
            update_fields=[
                "normalized_name",
                "is_standard",
                "needs_review",
            ]
        )

    seen_overhead = set()

    for overhead_type in OverheadType.objects.order_by("pk"):
        key = (overhead_type.assembly_id, normalize(overhead_type.name))
        normalized_name = key[1]

        if key in seen_overhead:
            normalized_name = f"{normalized_name} legacy {overhead_type.pk}"

        seen_overhead.add(key)

        overhead_type.normalized_name = normalized_name

        # Scope must agree with valid_overhead_type_scope:
        # - assembly=None means global
        # - assembly set means assembly-specific
        overhead_type.is_global = overhead_type.assembly_id is None
        overhead_type.needs_review = overhead_type.assembly_id is not None

        overhead_type.save(
            update_fields=[
                "normalized_name",
                "is_global",
                "needs_review",
            ]
        )

    for name, reporting_group in REVENUE_STANDARDS:
        RevenueCategory.objects.get_or_create(
            assembly=None,
            normalized_name=normalize(name),
            defaults={
                "name": name,
                "is_standard": True,
                "is_active": True,
                "reporting_group": reporting_group,
                "needs_review": False,
            },
        )

    for name, reporting_group in OVERHEAD_STANDARDS:
        OverheadType.objects.get_or_create(
            assembly=None,
            normalized_name=normalize(name),
            defaults={
                "name": name,
                "is_global": True,
                "is_active": True,
                "reporting_group": reporting_group,
                "needs_review": False,
            },
        )


def noop_reverse(apps, schema_editor):
    # Seed rows may already be referenced by financial entries; keep them on rollback.
    pass


class Migration(migrations.Migration):
    # RunPython writes category rows before this migration adds constraints
    # to those same PostgreSQL tables. Commit operations independently so
    # FK trigger events are resolved before ALTER TABLE.
    atomic = False

    dependencies = [
        ('bookkeeper', '0069_alter_expenditure_options_expenditure_timestamp_and_more'),
        ('churches', '0051_alter_church_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='overheadtype',
            name='unique_overhead_type_per_assembly',
        ),
        migrations.AlterUniqueTogether(
            name='revenuecategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='overheadtype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='overheadtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_overhead_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overheadtype',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='overheadtype',
            name='normalized_name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='overheadtype',
            name='reporting_group',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='overheadtype',
            name='standard_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overhead_aliases', to='bookkeeper.overheadtype'),
        ),
        migrations.AddField(
            model_name='revenuecategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='revenuecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_revenue_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenuecategory',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revenuecategory',
            name='normalized_name',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='revenuecategory',
            name='reporting_group',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='revenuecategory',
            name='standard_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_aliases', to='bookkeeper.revenuecategory'),
        ),
        migrations.AlterField(
            model_name='revenuecategory',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='churches.church'),
        ),
        migrations.RunPython(populate_category_metadata, noop_reverse),
        migrations.AddConstraint(
            model_name='overheadtype',
            constraint=models.UniqueConstraint(fields=('assembly', 'normalized_name'), name='unique_normalized_overhead_type_per_assembly'),
        ),
        migrations.AddConstraint(
            model_name='overheadtype',
            constraint=models.UniqueConstraint(condition=models.Q(('assembly__isnull', True), ('is_global', True)), fields=('normalized_name',), name='unique_standard_overhead_type_name'),
        ),
        migrations.AddConstraint(
            model_name='overheadtype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assembly__isnull', True), ('is_global', True)), models.Q(('assembly__isnull', False), ('is_global', False)), _connector='OR'), name='valid_overhead_type_scope'),
        ),
        migrations.AddConstraint(
            model_name='overheadtype',
            constraint=models.CheckConstraint(condition=models.Q(('is_global', True), ('standard_category__isnull', False), ('needs_review', True), _connector='OR'), name='overhead_type_mapping_or_review'),
        ),
        migrations.AddConstraint(
            model_name='revenuecategory',
            constraint=models.UniqueConstraint(fields=('assembly', 'normalized_name'), name='unique_normalized_revenue_category_per_assembly'),
        ),
        migrations.AddConstraint(
            model_name='revenuecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('assembly__isnull', True), ('is_standard', True)), fields=('normalized_name',), name='unique_standard_revenue_category_name'),
        ),
        migrations.AddConstraint(
            model_name='revenuecategory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assembly__isnull', True), ('is_standard', True)), models.Q(('assembly__isnull', False), ('is_standard', False)), _connector='OR'), name='valid_revenue_category_scope'),
        ),
        migrations.AddConstraint(
            model_name='revenuecategory',
            constraint=models.CheckConstraint(condition=models.Q(('is_standard', True), ('standard_category__isnull', False), ('needs_review', True), _connector='OR'), name='revenue_category_mapping_or_review'),
        ),
    ]
