# Generated by Django 5.2.16 on 2026-08-30 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0071_remittance_obligations_and_payments'),
        ('churches', '0051_alter_church_code'),
        ('people', '0072_historical_attendance_and_sunday_school_report'),
        ('reports', '0024_historical_migration_foundation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='overhead',
            name='unique_report_overhead_type',
        ),
        migrations.RemoveConstraint(
            model_name='revenue',
            name='unique_report_category',
        ),
        migrations.RemoveConstraint(
            model_name='tithe',
            name='unique_report_member_tithe',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='is_trash',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='trash_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overhead',
            name='is_trash',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='overhead',
            name='trash_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='is_trash',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='revenue',
            name='trash_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variable_expenditure_set', to='reports.assemblyreport'),
        ),
        migrations.AlterField(
            model_name='tithe',
            name='is_trash',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='overhead',
            constraint=models.UniqueConstraint(condition=models.Q(('is_trash', False)), fields=('report', 'overhead_type'), name='unique_report_overhead_type'),
        ),
        migrations.AddConstraint(
            model_name='revenue',
            constraint=models.UniqueConstraint(condition=models.Q(('is_trash', False)), fields=('report', 'category'), name='unique_report_category'),
        ),
        migrations.AddConstraint(
            model_name='tithe',
            constraint=models.UniqueConstraint(condition=models.Q(('is_trash', False)), fields=('report', 'member'), name='unique_report_member_tithe'),
        ),
    ]
