# Generated by Django 6.0.3 on 2026-10-07 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0072_remove_overhead_unique_report_overhead_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTitheReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('receipt_data', models.JSONField(default=dict)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('last_printed_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tithe_receipts', to=settings.AUTH_USER_MODEL)),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_tithe_receipts', to=settings.AUTH_USER_MODEL)),
                ('tithe', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generated_receipt', to='bookkeeper.tithe')),
            ],
        ),
    ]
