# Generated by Django 6.0.3 on 2026-07-20 07:21

import apps.jethro.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0069_alter_expenditure_options_expenditure_timestamp_and_more'),
        ('churches', '0051_alter_church_code'),
        ('jethro', '0001_initial'),
        ('people', '0071_remove_membertransferrequest_unique_pending_transfer_per_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JethroTitheDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=apps.jethro.models.generate_public_id, editable=False, max_length=21, unique=True)),
                ('member_query', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=26)),
                ('payment_date', models.DateField()),
                ('reference_code', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('original_request', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('pending_member_selection', 'Pending member selection'), ('pending_confirmation', 'Pending confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='pending_member_selection', max_length=30)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jethro_tithe_drafts', to='churches.church')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tithe_drafts', to='jethro.jethroconversation')),
                ('created_tithe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jethro_drafts', to='bookkeeper.tithe')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jethro_tithe_drafts', to='people.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jethro_tithe_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'assembly', 'status'], name='jethro_jeth_user_id_f55478_idx')],
            },
        ),
    ]
