# Generated by Django 4.2.1 on 2023-07-06 00:36

import apps.users.utils
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('surname', models.CharField(max_length=255, verbose_name='surname')),
                ('username', models.CharField(max_length=36, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.users.utils.avatarURL)),
                ('avatar_fallback', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_pastor', models.BooleanField(default=False)),
                ('is_secretary', models.BooleanField(default=False)),
                ('is_overseer', models.BooleanField(default=False)),
                ('church', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church', to='church.church')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=255)),
                ('method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Visa', 'Visa'), ('Mastercard', 'Mastercard')], max_length=255)),
                ('intervals', models.IntegerField(choices=[(1, 'Monthly'), (4, 'Quarterly'), (12, 'Annually')], default=0)),
                ('premium_fee', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ['-created'],
            },
        ),
    ]
