# Generated by Django 4.2.1 on 2023-05-28 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_alter_attendance_options_alter_demographics_options_and_more'),
        ('users', '0002_alter_user_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church', to='church.church'),
        ),
    ]
