# Generated by Django 4.2.3 on 2023-10-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0007_church_currency'),
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='churches',
            field=models.ManyToManyField(blank=True, related_name='branches', to='churches.church'),
        ),
    ]
