# Generated by Django 4.2.3 on 2023-12-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('President', 'President'), ('Senior Pastor', 'Senior Pastor'), ('Overseer', 'Overseer'), ('Moderator', 'Moderator'), ('Pastor', 'Pastor'), ('Secretary', 'Secretary'), ('Admin', 'Admin')], max_length=24),
        ),
    ]
