# Generated by Django 4.2.3 on 2024-01-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_overseer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pastor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_president',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_secretary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_senior_pastor',
        ),
    ]
