# Generated by Django 4.2.9 on 2024-09-06 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_last_logout_alter_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('President', 'President'), ('Senior Pastor', 'Senior Pastor'), ('Overseer', 'Overseer'), ('Moderator', 'Moderator'), ('Pastor', 'Pastor'), ('Secretary', 'Secretary'), ('Secretary General', 'Secretary General'), ('Admin', 'Admin'), ('Delegate', 'Delegate')], default='Secretary', max_length=24),
        ),
        migrations.CreateModel(
            name='DelegatePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('permission_type', models.CharField(choices=[('finance', 'Finance'), ('attendance', 'Attendance')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'permission_type')},
            },
        ),
    ]
