# Generated by Django 4.2.9 on 2025-01-20 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_role_delegatepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at'], 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='account',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='account',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='account',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='account',
            name='intervals',
        ),
        migrations.RemoveField(
            model_name='account',
            name='method',
        ),
        migrations.RemoveField(
            model_name='account',
            name='premium_fee',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
