# Generated by Django 4.2.9 on 2025-01-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_account_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Profile',
        ),
    ]
