# Generated by Django 4.2.9 on 2025-01-20 10:01

import apps.users.utils
from django.db import migrations, models
import imagekit.models.fields

import apps.users.utils.base_urls


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_account_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.users.utils.base_urls.user_avatar_url),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_fallback',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=26),
        ),
        migrations.AddField(
            model_name='profile',
            name='iso_country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
