# Generated by Django 4.2.9 on 2025-01-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_avatar_profile_avatar_fallback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state_or_province',
            field=models.CharField(blank=True, max_length=26),
        ),
    ]
