# Generated by Django 4.2.9 on 2025-01-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_state_or_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='churches',
            new_name='assemblies',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Delegate', 'Delegate'), ('Dean', 'Dean'), ('Moderator', 'Moderator'), ('Overseer', 'Overseer'), ('Pastor', 'Pastor'), ('President', 'President'), ('Secretary', 'Secretary'), ('Secretary General', 'Secretary General'), ('Senior Pastor', 'Senior Pastor'), ('Student', 'Student'), ('Student Representative', 'Student Representative')], default='Secretary', max_length=24),
        ),
    ]
