# Generated by Django 4.2.9 on 2025-01-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_churches_user_assemblies_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Admin', 'Admin'), ('Delegate', 'Delegate'), ('Dean', 'Dean'), ('Moderator', 'Moderator'), ('Overseer', 'Overseer'), ('Pastor', 'Pastor'), ('President', 'President'), ('Secretary', 'Secretary'), ('Secretary General', 'Secretary General'), ('Senior Pastor', 'Senior Pastor'), ('Student', 'Student'), ('Student Representative', 'Student Representative')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.role'),
        ),
    ]
