# Generated by Django 4.2.9 on 2025-03-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_role_remove_user_role_user_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
    ]
