# Generated by Django 4.2.9 on 2025-04-12 11:18

import apps.users.utils
from django.db import migrations, models

import apps.users.utils.nanoid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_is_onboarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=apps.users.utils.nanoid.generate_nanoid, editable=False, max_length=32, unique=True),
        ),
    ]
