# Generated by Django 4.2.9 on 2025-04-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_email',
            field=models.EmailField(blank=True, help_text='Used for account recovery or alternative communication.', max_length=254, null=True, unique=True),
        ),
    ]
