# Generated by Django 4.2.9 on 2025-04-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_recovery_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_fallback',
            field=models.CharField(blank=True, max_length=26),
        ),
    ]
