# Generated by Django 4.2.9 on 2025-04-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_avatar_fallback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Delegate', 'Delegate'), ('Dean', 'Dean'), ('Moderator', 'Moderator'), ('Overseer', 'Overseer'), ('Pastor', 'Pastor'), ('President', 'President'), ('Secretary', 'Secretary'), ('Secretary General', 'Secretary General'), ('Senior Pastor', 'Senior Pastor'), ('Student', 'Student'), ('Student Representative', 'Student Representative'), ('TEACHER', 'TEACHER')], max_length=50, unique=True),
        ),
    ]
