# Generated by Django 4.2.9 on 2025-09-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Dean', 'Dean'), ('Moderator', 'Moderator'), ('Overseer', 'Overseer'), ('Pastor', 'Pastor'), ('President', 'President'), ('Secretary', 'Secretary'), ('Secretary General', 'Secretary General'), ('Senior Pastor', 'Senior Pastor'), ('Student', 'Student'), ('Student Representative', 'Student Representative'), ('Teacher', 'Teacher'), ('Zone Admin', 'Zone Admin')], max_length=50, unique=True),
        ),
    ]
