# Generated by Django 6.0.3 on 2026-06-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_fallback',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
