# Generated by Django 6.0.3 on 2026-08-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_user_avatar_fallback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recovery_email',
            field=models.EmailField(blank=True, help_text='Personal email used for password recovery and account security notifications.', max_length=254, null=True, unique=True, verbose_name='Recovery Email'),
        ),
    ]
