# Generated by Django 4.2.1 on 2023-06-12 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_remove_demographics_church_remove_member_church_and_more'),
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='members',
            name='contacts',
        ),
        migrations.AddField(
            model_name='members',
            name='phone',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='church.church'),
        ),
    ]
