# Generated by Django 4.2.3 on 2023-07-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['last_name'], 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
        migrations.RenameField(
            model_name='members',
            old_name='surname',
            new_name='last_name',
        ),
    ]
