# Generated by Django 4.2.3 on 2023-07-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0002_alter_members_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='timetable',
        ),
    ]
