# Generated by Django 4.2.1 on 2023-06-25 09:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_remove_demographics_church_remove_member_church_and_more'),
        ('demographics', '0002_rename_name_members_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='tithes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='members',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='church.church'),
        ),
    ]
