# Generated by Django 4.2.1 on 2023-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0003_members_tithes_alter_members_church'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='date_of_baptism',
            new_name='baptism_date',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='work',
            new_name='city',
        ),
        migrations.AddField(
            model_name='members',
            name='profession',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='members',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255),
        ),
        migrations.AlterField(
            model_name='members',
            name='ministry',
            field=models.CharField(blank=True, choices=[('Media', 'Media'), ('Ushering', 'Ushering'), ('Praise and Worship', 'Praise and Worship'), ('Intercession', 'Intercession'), ('House Keeping and Maintenance', 'House Keeping and Maintenance')], max_length=255),
        ),
        migrations.AlterField(
            model_name='members',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Engaged', 'Engaged'), ('In a Relationship', 'In a Relationship'), ('Domestic Partnership', 'Domestic Partnership'), ('Civil Union', 'Civil Union'), ('Committed', 'Committed'), ('Common-Law Marriage', 'Common-Law Marriage'), ('Traditional Marriage', 'Traditional Marriage'), ('Co-parenting', 'Co-parenting')], max_length=255),
        ),
        migrations.AlterField(
            model_name='members',
            name='role',
            field=models.CharField(blank=True, choices=[('Sunday School Teacher', 'Sunday School Teacher'), ('Youth Leader', 'Youth Leader'), ('Deacon', 'Deacon'), ('Deaconess', 'Deaconess'), ('Elder', 'Elder'), ('Praise and Worship Director', 'Praise and Worship Director'), ('Pastor', 'Pastor'), ('Senior Pastor', 'Senior Pastor'), ('Overseer', 'Overseer'), ('President', 'President'), ('Media Director', 'Media Director'), ('WOE Leader', 'WOE Leader'), ('Gatekeepers Leader', 'Gatekeepers Leader'), ('House Keeper', 'House Keeper'), ('Home Cell Leader', 'Home Cell Leader'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Other', 'Other')], max_length=255),
        ),
    ]
