# Generated by Django 4.2.1 on 2023-06-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0004_rename_date_of_baptism_members_baptism_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='profession',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='role',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='members',
            name='title',
        ),
        migrations.AddField(
            model_name='members',
            name='prefix',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=255),
        ),
        migrations.AlterField(
            model_name='members',
            name='ministry',
            field=models.CharField(blank=True, choices=[('Administration', 'Administration'), ('Christian education', 'Christian education'), ('Counseling', 'Counseling'), ('Discernment', 'Discernment'), ('Evangelism', 'Evangelism'), ('Giving', 'Giving'), ('Hospitality', 'Hospitality'), ('Intercession', 'Intercession'), ('Leadership', 'Leadership'), ('Media and Communications', 'Media and Communications'), ('Other', 'Other'), ('Praise and Worship', 'Praise and Worship'), ('Ushering', 'Ushering')], max_length=255),
        ),
    ]
