from django.db import models

class ChurchRoles(models.TextChoices):
    DEACON = 'Deacon', 'Deacon'
    DEACONESS = 'Deaconess', 'Deaconess'
    ELDER = 'Elder', 'Elder'
    GATEKEEPERS_LEADER = 'Gatekeepers Leader', 'Gatekeepers Leader'
    GENERAL_OVERSEER = 'General Overseer', 'General Overseer'
    HOUSE_KEEPER = 'House Keeper', 'House Keeper'
    HOME_CELL_LEADER = 'Home Cell Leader', 'Home Cell Leader'
    MEDIA_DIRECTOR = 'Media Director', 'Media Director'
    NATIONAL_OVERSEER = 'National Overseer', 'National Overseer'
    OTHER = 'Other', 'Other'
    PASTOR = 'Pastor', 'Pastor'
    PRAISE_AND_WORSHIP_DIRECTOR = 'Praise and Worship Director', 'Praise and Worship Director'
    PRESIDENT = 'President', 'President'
    SECRETARY = 'Secretary', 'Secretary'
    SECRETARY_GENERAL = 'Secretary General', 'Secretary General'
    SENIOR_PASTOR = 'Senior Pastor', 'Senior Pastor'
    SUNDAY_SCHOOL_TEACHER = 'Sunday School Teacher', 'Sunday School Teacher'
    TREASURER = 'Treasurer', 'Treasurer'
    USHER = 'Usher', 'Usher'
    WOE_LEADER = 'WOE Leader', 'WOE Leader'
    YOUTH_LEADER = 'Youth Leader', 'Youth Leader'


class Ministries(models.TextChoices):
    ADMINISTRATION = 'Administration', 'Administration'
    CHRISTIAN_EDUCATION = 'Christian Education', 'Christian Education'
    COUNSELING = 'Counseling', 'Counseling'
    DISCERNMENT = 'Discernment', 'Discernment'
    EVANGELISM = 'Evangelism', 'Evangelism'
    GIVING = 'Giving', 'Giving'
    HOSPITALITY = 'Hospitality', 'Hospitality'
    INTERCESSION = 'Intercession', 'Intercession'
    LEADERSHIP = 'Leadership', 'Leadership'
    MEDIA = 'Media and Communications', 'Media and Communications'
    OTHER = 'Other', 'Other'
    PRAISE_AND_WORSHIP = 'Praise and Worship', 'Praise and Worship'
    SUNDAY_SCHOOL = 'Sunday School', 'Sunday School'
    USHERING = 'Ushering', 'Ushering'