from typing import Any, TYPE_CHECKING
from rest_framework.request import Request

if TYPE_CHECKING:

    from rest_framework.serializers import Serializer

class ViewSetMixinBase:
    def get_queryset(self) -> Any: ...
    def get_object(self) -> Any: ...
    def get_serializer(self, *args, **kwargs) -> Any: ...
    
    def perform_create(self, serializer) -> Any: ...
    def perform_update(self, serializer) -> Any: ...
    def perform_destroy(self, instance) -> Any: ...
