# Generated by Django 6.0.3 on 2026-07-16 08:40

import apps.examinations.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBAStudentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveBigIntegerField(unique=True)),
                ('student_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('source_username', models.UUIDField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(default='student', max_length=50)),
                ('avatar', models.URLField(blank=True)),
                ('avatar_fallback', models.CharField(blank=True, max_length=32)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'student_number'],
                'indexes': [models.Index(fields=['student_number'], name='examination_student_dac5db_idx'), models.Index(fields=['last_name', 'first_name'], name='examination_last_na_22331d_idx'), models.Index(fields=['is_active', 'role'], name='examination_is_acti_db4094_idx')],
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('academic_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('examination_date', models.DateField(blank=True, null=True)),
                ('total_marks', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=7)),
                ('pass_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_examinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year', 'name', '-created_at'],
                'permissions': [('manage_examinations', 'Can manage examinations')],
            },
        ),
        migrations.CreateModel(
            name='ExaminationImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to=apps.examinations.models.examination_pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('review_required', 'Review required'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=30)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('matched_rows', models.PositiveIntegerField(default=0)),
                ('unmatched_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('excluded_rows', models.PositiveIntegerField(default=0)),
                ('parser_version', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='examinations.examination')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examination_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_student_number', models.CharField(max_length=100)),
                ('normalized_student_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('raw_result', models.CharField(max_length=255)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('result_status', models.CharField(blank=True, choices=[('scored', 'Scored'), ('absent', 'Absent'), ('withheld', 'Withheld'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Student not found'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid'), ('excluded', 'Excluded')], default='unmatched', max_length=20)),
                ('validation_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='examinations.examinationimport')),
                ('matched_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_examination_import_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number_snapshot', models.CharField(db_index=True, max_length=100)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('status', models.CharField(choices=[('scored', 'Scored'), ('absent', 'Absent'), ('withheld', 'Withheld'), ('cancelled', 'Cancelled')], default='scored', max_length=20)),
                ('raw_imported_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.examination')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_results', to='examinations.examinationimport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examination_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_number_snapshot'],
            },
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['academic_year', 'name'], name='examination_academi_ee3d00_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['status'], name='examination_status_0fcf47_idx'),
        ),
        migrations.AddConstraint(
            model_name='examination',
            constraint=models.CheckConstraint(condition=models.Q(('total_marks__gt', 0)), name='examination_total_marks_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='examinationimport',
            index=models.Index(fields=['examination', 'status'], name='examination_examina_b9b17b_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationimport',
            index=models.Index(fields=['status', 'created_at'], name='examination_status_e20b82_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationimportrow',
            index=models.Index(fields=['import_batch', 'match_status'], name='examination_import__7d5c82_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationimportrow',
            index=models.Index(fields=['import_batch', 'normalized_student_number'], name='examination_import__0ec397_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationresult',
            index=models.Index(fields=['examination', 'status'], name='examination_examina_177eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationresult',
            index=models.Index(fields=['student', 'examination'], name='examination_student_8c7deb_idx'),
        ),
        migrations.AddConstraint(
            model_name='examinationresult',
            constraint=models.UniqueConstraint(fields=('examination', 'student'), name='unique_student_result_per_examination'),
        ),
        migrations.AddConstraint(
            model_name='examinationresult',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), ('score__gte', 0), _connector='OR'), name='examination_result_score_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='examinationresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('score__isnull', False), ('status', 'scored')), models.Q(('score__isnull', True), ('status__in', ['absent', 'withheld', 'cancelled'])), _connector='OR'), name='examination_result_status_matches_score'),
        ),
    ]
