# Generated by Django 4.2.9 on 2025-10-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unifiedreport',
            old_name='finalized_date',
            new_name='finalized_at',
        ),
    ]
