# Generated by Django 4.2.9 on 2025-10-12 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_rename_finalized_date_unifiedreport_finalized_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedreport',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
