# Generated by Django 4.2.9 on 2026-02-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_unifiedreport_finalized_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedreport',
            name='period_end',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='period_start',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='unifiedreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='unifiedreport',
            index=models.Index(fields=['church', 'status'], name='reports_uni_church__a1e3d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='unifiedreport',
            constraint=models.UniqueConstraint(fields=('church', 'period_start', 'period_end'), name='unique_assembly_report_period'),
        ),
    ]
