# Generated by Django 4.2.9 on 2026-02-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_unifiedreport_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedreport',
            name='attendance_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unifiedreport',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='unifiedreport',
            name='expense_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='unifiedreport',
            name='income_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='unifiedreport',
            name='members_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unifiedreport',
            name='tithe_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddIndex(
            model_name='unifiedreport',
            index=models.Index(fields=['period_start'], name='reports_uni_period__5b5df5_idx'),
        ),
    ]
