# Generated by Django 4.2.9 on 2026-02-27 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0055_alter_fixedexpenditure_report_alter_income_report_and_more'),
        ('churches', '0033_alter_zone_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0055_attendance_special_event_name_and_more'),
        ('reports', '0005_unifiedreport_attendance_total_unifiedreport_balance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnifiedReport',
            new_name='AssemblyReport',
        ),
        migrations.RenameIndex(
            model_name='assemblyreport',
            new_name='reports_ass_church__dfc98e_idx',
            old_name='reports_uni_church__a1e3d0_idx',
        ),
        migrations.RenameIndex(
            model_name='assemblyreport',
            new_name='reports_ass_period__0a83f0_idx',
            old_name='reports_uni_period__5b5df5_idx',
        ),
    ]
