# Generated by Django 4.2.9 on 2026-02-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_reportrejection'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assemblyreport',
            name='reports_ass_church__dfc98e_idx',
        ),
        migrations.RemoveIndex(
            model_name='assemblyreport',
            name='reports_ass_period__0a83f0_idx',
        ),
        migrations.AlterField(
            model_name='assemblyreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
