# Generated by Django 4.2.9 on 2026-03-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_assemblyreport_reports_ass_church__dfc98e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrejection',
            name='revision_number',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='reportrejection',
            unique_together={('report', 'revision_number')},
        ),
    ]
