# Generated by Django 4.2.9 on 2026-03-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_assemblyreport_options_auditlog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assemblyreport',
            name='unique_assembly_report_period',
        ),
        migrations.RenameField(
            model_name='assemblyreport',
            old_name='church',
            new_name='assembly',
        ),
        migrations.AddConstraint(
            model_name='assemblyreport',
            constraint=models.UniqueConstraint(fields=('assembly', 'period_start', 'period_end'), name='unique_assembly_report_period'),
        ),
    ]
