# Generated by Django 4.2.9 on 2026-03-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_assemblyreport_unique_assembly_report_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyreport',
            name='total_adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='total_baptisms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='total_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='total_guests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='total_new_converts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='total_online_viewers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
