# Generated by Django 4.2.9 on 2026-03-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_assemblyreport_total_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
