# Generated by Django 4.2.9 on 2026-03-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auditlog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
