# Generated by Django 4.2.9 on 2026-03-04 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0033_alter_zone_code'),
        ('reports', '0014_alter_auditlog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_assemblies', models.PositiveIntegerField(default=0)),
                ('compliant_assemblies', models.PositiveIntegerField(default=0)),
                ('compliance_rate', models.FloatField(default=0)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='churches.zone')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('zone', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AssemblyCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('LATE', 'Late'), ('NOT_SUBMITTED', 'Not Submitted'), ('NOT_FINALIZED', 'Not Finalized'), ('MISSING_FROM_ZONE', 'Missing From Zone')], max_length=30)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='churches.church')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.assemblyreport')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_compliance', to='churches.zone')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('assembly', 'year', 'month')},
            },
        ),
    ]
