# Generated by Django 6.0.3 on 2026-06-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('finalized', 'finalized'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ReportSectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('attendance', 'Attendance'), ('tithes', 'Tithes'), ('income', 'Income'), ('expenditure', 'Expenditure'), ('remittance', 'Remittance'), ('junior_members', 'Junior Members')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('skip_reason', models.CharField(blank=True, choices=[('no_data', 'No data available'), ('not_collected', 'Statistics were not collected'), ('not_applicable', 'Not applicable'), ('technical_issue', 'Technical issue'), ('other', 'Other')], max_length=30, null=True)),
                ('skip_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.assemblyreport')),
            ],
            options={
                'unique_together': {('report', 'section')},
            },
        ),
    ]
