# Generated by Django 6.0.3 on 2026-06-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_rename_finalized_at_assemblyreport_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblycompliance',
            name='compliance_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assemblycompliance',
            name='consistency_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assemblycompliance',
            name='overall_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assemblycompliance',
            name='risk_level',
            field=models.CharField(default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='assemblycompliance',
            name='timeliness_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assemblycompliance',
            name='trend',
            field=models.CharField(default='stable', max_length=20),
        ),
        migrations.AddField(
            model_name='zonecompliance',
            name='compliance_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zonecompliance',
            name='consistency_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zonecompliance',
            name='overall_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zonecompliance',
            name='risk_level',
            field=models.CharField(default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='zonecompliance',
            name='timeliness_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zonecompliance',
            name='trend',
            field=models.CharField(default='stable', max_length=20),
        ),
        migrations.AlterField(
            model_name='assemblyreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
