# Generated by Django 6.0.3 on 2026-08-02 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_report_sections(apps, schema_editor):
    AssemblyReport = apps.get_model("reports", "AssemblyReport")
    ReportSectionStatus = apps.get_model("reports", "ReportSectionStatus")
    section_sources = {
        "general_attendance": ("general_attendance", "attendance"),
        "sunday_school_attendance": ("sunday_school_attendance", "junior_members"),
        "tithes": ("tithes",),
        "revenue": ("revenue", "income"),
        "operating_expenses": ("operating_expenses", "remittance"),
        "activity_other_expenses": ("activity_other_expenses", "expenditure"),
    }
    status_map = {
        "pending": "not_started",
        "submitted": "completed",
    }
    reason_map = {
        "no_data": "records_unavailable",
        "not_collected": "information_pending",
        "not_applicable": "activity_did_not_take_place",
        "technical_issue": "technical_problem",
    }
    status_priority = {"submitted": 3, "completed": 3, "skipped": 2, "pending": 1}

    for report in AssemblyReport.objects.all().iterator():
        for canonical, source_keys in section_sources.items():
            candidates = list(
                ReportSectionStatus.objects.filter(report=report, section__in=source_keys)
            )
            if candidates:
                keeper = max(candidates, key=lambda row: status_priority.get(row.status, 0))
                for duplicate in candidates:
                    if duplicate.pk != keeper.pk:
                        duplicate.delete()
                keeper.section = canonical
                keeper.status = status_map.get(keeper.status, keeper.status)
                keeper.skip_reason = reason_map.get(keeper.skip_reason, keeper.skip_reason)
                keeper.save(update_fields=["section", "status", "skip_reason"])
            else:
                ReportSectionStatus.objects.create(
                    report=report,
                    section=canonical,
                    status="not_started",
                )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_assemblyreport_visitor_and_altar_totals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyreport',
            name='amendment_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='amendment_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='amendment_started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_report_amendments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='editable_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsectionstatus',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsectionstatus',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_report_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportsectionstatus',
            name='no_activity_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsectionstatus',
            name='no_activity_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_no_activity_report_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportsectionstatus',
            name='no_activity_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsectionstatus',
            name='skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsectionstatus',
            name='skipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skipped_report_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportsectionstatus',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsectionstatus',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_report_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_report_sections, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reportsectionstatus',
            name='section',
            field=models.CharField(choices=[('general_attendance', 'General Attendance'), ('sunday_school_attendance', 'Sunday School Attendance'), ('tithes', 'Tithes'), ('revenue', 'Revenue'), ('operating_expenses', 'Operating Expenses'), ('activity_other_expenses', 'Activity & Other Expenses')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reportsectionstatus',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('records_unavailable', 'Records unavailable'), ('responsible_person_unavailable', 'Responsible person unavailable'), ('technical_problem', 'Technical problem'), ('records_lost_or_damaged', 'Records lost or damaged'), ('activity_did_not_take_place', 'Activity did not take place'), ('information_pending', 'Information pending'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reportsectionstatus',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('no_activity', 'No activity'), ('skipped', 'Skipped')], default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField()),
                ('editable_until', models.DateTimeField()),
                ('declaration_confirmed', models.BooleanField(default=False)),
                ('validation_findings', models.JSONField(blank=True, default=list)),
                ('attendance_total', models.PositiveIntegerField(default=0)),
                ('sunday_school_attendance_total', models.PositiveIntegerField(default=0)),
                ('tithe_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('operating_expense_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('activity_other_expense_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='reports.assemblyreport')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_report_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ReportSectionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=list)),
                ('source_references', models.JSONField(blank=True, default=dict)),
                ('skip_reason_code', models.CharField(blank=True, max_length=40, null=True)),
                ('skip_reason_detail', models.TextField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('no_activity_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('no_activity_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('no_activity_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_no_activity_section_snapshots', to=settings.AUTH_USER_MODEL)),
                ('skipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_skipped_section_snapshots', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_snapshots', to='reports.reportversion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='amendment_base_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='based_amendments', to='reports.reportversion'),
        ),
        migrations.AddField(
            model_name='assemblyreport',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_reports', to='reports.reportversion'),
        ),
        migrations.CreateModel(
            name='ReportReopeningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('request_reason', models.TextField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopening_requests', to='reports.assemblyreport')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_reopening_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_report_reopening_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'requested')), fields=('report',), name='unique_active_report_reopening_request')],
            },
        ),
        migrations.AddConstraint(
            model_name='reportversion',
            constraint=models.UniqueConstraint(fields=('report', 'version_number'), name='unique_report_version_number'),
        ),
        migrations.AddConstraint(
            model_name='reportsectionsnapshot',
            constraint=models.UniqueConstraint(fields=('version', 'section'), name='unique_report_version_section_snapshot'),
        ),
    ]
