# Generated by Django 4.2.3 on 2023-11-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategylegacy',
            name='color',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
