# Generated by Django 4.2.3 on 2023-11-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0002_strategylegacy_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategylegacy',
            name='coordinator',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
