# Generated by Django 4.2.3 on 2023-12-12 06:19

import apps.strategic.helpers
from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0003_alter_strategylegacy_coordinator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='accountability',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='capacity_development',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='church_growth',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='financial_mandate',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='humanitarian_projects',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='infrastructure_development',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='introduction',
        ),
        migrations.AddField(
            model_name='strategy',
            name='banner',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.strategic.helpers.strategy_banner_path),
        ),
        migrations.AddField(
            model_name='strategy',
            name='banner_fallback',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='strategy',
            name='coordinator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='strategy',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
