# Generated by Django 4.2.3 on 2023-12-12 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategic', '0004_rename_accountability_strategy_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_plan_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
