# Generated by Django 4.2.3 on 2023-12-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0005_strategy_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=255),
        ),
    ]
