# Generated by Django 4.2.3 on 2023-12-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic', '0006_strategy_feedback_strategy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategylegacy',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
