# Generated by Django 4.2.3 on 2023-10-07 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ['-created_at'], 'verbose_name': 'strategy', 'verbose_name_plural': 'strategies'},
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='strategy',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='file',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
