# Generated by Django 4.2.3 on 2023-10-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_alter_strategy_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='file_id',
            new_name='strategy_id',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='filename',
            new_name='title',
        ),
    ]
