# Generated by Django 4.2.3 on 2023-10-16 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churches', '0007_church_currency'),
        ('strategy', '0005_rename_file_id_strategy_strategy_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyLegacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='documents/strategy')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('timestamp', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to='churches.church')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_coordinator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'strategy',
                'verbose_name_plural': 'strategies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
