# Generated by Django 4.2.3 on 2023-10-16 16:40

import apps.strategy.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0007_church_currency'),
        ('strategy', '0006_strategylegacy_delete_strategy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategylegacy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Strategy Legacy', 'verbose_name_plural': 'Strategy Legacy'},
        ),
        migrations.RemoveField(
            model_name='strategylegacy',
            name='church',
        ),
        migrations.AddField(
            model_name='strategylegacy',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_legacy', to='churches.church'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategylegacy',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.strategy.models.strategy_file_path),
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('introduction', models.TextField(blank=True)),
                ('financial_mandate', models.TextField(blank=True)),
                ('capacity_development', models.TextField(blank=True)),
                ('infrastructure_development', models.TextField(blank=True)),
                ('church_growth', models.TextField(blank=True)),
                ('humanitarian_projects', models.TextField(blank=True)),
                ('accountability', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to='churches.church')),
            ],
            options={
                'verbose_name': 'strategy',
                'verbose_name_plural': 'strategies',
                'ordering': ['-created_at'],
            },
        ),
    ]
