# Generated by Django 4.2.3 on 2023-12-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_post_reply_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.CharField(choices=[('Attendance', 'Attendance'), ('Authentication', 'Authentication'), ('Demographics', 'Demographics'), ('Finance', 'Finance'), ('General', 'General'), ('Strategy', 'Strategy'), ('Updates', 'Updates')], default='General', max_length=255),
        ),
    ]
