# Generated by Django 4.2.3 on 2023-12-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forum_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at'], 'verbose_name': 'reply', 'verbose_name_plural': 'replies'},
        ),
    ]
