# Generated by Django 4.2.3 on 2023-12-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_reply_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.CharField(choices=[('Attendance', 'Attendance'), ('Authentication', 'Authentication'), ('Changelog', 'Changelog'), ('Demographics', 'Demographics'), ('Finance', 'Finance'), ('General', 'General'), ('Strategy', 'Strategy'), ('Updates', 'Updates')], default='General', max_length=255),
        ),
    ]
