# Generated by Django 4.2.9 on 2024-06-09 12:30

import apps.forum.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0006_alter_forum_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Attendance', 'Attendance'), ('Authentication', 'Authentication'), ('Changelog', 'Changelog'), ('Demographics', 'Demographics'), ('Finance', 'Finance'), ('General', 'General'), ('Strategy', 'Strategy'), ('Templates', 'Templates'), ('Updates', 'Updates')], default='General', max_length=255)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.forum.helpers.forum_image_path)),
                ('views', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog_post_author', to=settings.AUTH_USER_MODEL)),
                ('read_by', models.ManyToManyField(blank=True, related_name='post_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'changelog',
                'verbose_name_plural': 'changelog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='discussion',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
