# Generated by Django 4.2.9 on 2024-06-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_changelog_remove_reply_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
