# Generated by Django 4.2.3 on 2023-12-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_likers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likers',
            new_name='likes',
        ),
    ]
