# Generated by Django 4.2.9 on 2025-05-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_rename_description_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='branch',
            new_name='assembly',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
    ]
