# Generated by Django 4.2.9 on 2025-05-09 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_rename_branch_post_assembly_rename_body_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_private',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('draft', 'Draft')], default='public', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('post', 'author')},
        ),
    ]
