# Generated by Django 4.2.9 on 2025-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_post_is_draft_remove_post_is_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='alt',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility and SEO.', max_length=255),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='caption',
            field=models.TextField(blank=True, help_text='Optional caption for the image.'),
        ),
    ]
