# Generated by Django 4.2.9 on 2024-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_desc_message_description_alter_message_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tag',
        ),
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('praise', 'Praise'), ('request', 'Request'), ('suggestion', 'Suggestion'), ('testimony', 'Testimony')], default='request', max_length=24),
        ),
        migrations.AlterField(
            model_name='message',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=24),
        ),
    ]
