# Generated by Django 4.2.9 on 2024-04-27 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_remove_message_contact_remove_message_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
