# Generated by Django 4.2.9 on 2024-04-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='church',
            new_name='assembly',
        ),
    ]
