# Generated by Django 4.2.9 on 2025-04-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_message_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_id',
            new_name='reference_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
    ]
