# Generated by Django 4.2.9 on 2025-04-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rename_message_id_message_reference_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='description',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='isMarkAsRead',
        ),
    ]
