# Generated by Django 4.2.9 on 2025-04-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_rename_description_message_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=24),
        ),
    ]
